### ISSUE TITLE
TOTP Authentication fails - debug: POST 2ndfactor totp: TOTP secret is null

### ISSUE THREAD

**Issue by Timinocobar** [clems4ever/authelia#103]
After succesfully implementing first factor authentication (LDAP), i wanted to use Google Authenticator as TOTP authentication. 

Scanning the QR-Code was successfull, but the login is still unsuccessfull. 
![image](https://user-images.githubusercontent.com/32493542/31140197-fdd5e352-a873-11e7-878f-059fb544e7d0.png)
The following message is written in the log:
_debug: AuthSession is {"first_factor":true,"second_factor":false,"groups":[],"userid":"Test","email":"test@test.local"}
info: POST 2ndfactor totp: Initiate TOTP validation for user Test
debug: POST 2ndfactor totp: Fetching secret for user Test
debug: POST 2ndfactor totp: TOTP secret is null
error: Reply with error 500: TypeError: Cannot read property 'secret' of null_

I get the same message typing in any letters in the token box.

Did I forgot any steps?

Thank you
Best regards
-Timinocobar-

**Comment by clems4ever** [comment]
Hello @Timinocobar , did you deploy Authelia with the provided steps in the README (docker-compose)? Did you change anything in the config? 
The use case is very simple and it is tested in Travis for sure. Hence, I'm interested in knowing what involves such a behavior.

Thanks.
Clément.

**Comment by Timinocobar** [comment]
I am not using docker, I only installed node and npm on a centos 7 vm.
Of course I made some changes to apply the config file to my environment, LDAP and Redis-Servers and so on.

**Comment by clems4ever** [comment]
I'm really interested in your deployment. Do you have an automated way to reproduce the infrastructure? Vagrant, Ansible, Chef? If yes, please post it or PM? If no, please post the version of Authelia and the configuration you are using.

For your info, the TOTP secret is stored in mongo and it should be in a collection called "totp_secrets". Can you please check there is something there with a CLI?

**Comment by clems4ever** [comment]
@Timinocobar , did you have time to check?

**Comment by clems4ever** [comment]
Please reopen the ticket if needed.
