### ISSUE TITLE
TOTP URL: custom issuer and label

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#109]
Hi,

I see you are using Speakeasy to generate TOTP secrets and URL. It would be great to support customized “label” and “issuer” options, in Authelia's YAML configuration file?

**Comment by clems4ever** [comment]
Hello @n4kre, I don't see anything on labels and issuers in the Speakeasy documentation. Do you know how to customize such things?

**Comment by n4kre** [comment]
I have searched for “label”, “name” and “issuer” on the description page of https://github.com/speakeasyjs/speakeasy and I thought it may be possible.

**Comment by clems4ever** [comment]
You are right, I see it in the README. Thanks.

**Comment by clems4ever** [comment]
Handled in #185
