### ISSUE TITLE
TOTP form: disable autocompletion

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#110]
Hi,

Autocompletion is enabled in the second factor submission form: it does not make sense, I guess, right?

**Comment by clems4ever** [comment]
Hello @n4kre , you are right, it does not make any sense. I will have a look on how I can fix it. Thank you.

**Comment by n4kre** [comment]
I guess `<input autocomplete="off" type="text" class="form-control" id="token" placeholder="Token" required autofocus>` in the second facor view would be enough – you may check.

**Comment by n4kre** [comment]
Detail: once the form is submitted, it would be nice to clear content of the TOTP field – upon failed login, the user thus wouldn't have to clear it “manually” before it tries again; upon successful login, it just looks weird.

**Comment by clems4ever** [comment]
Already merged in mainstream.
