### ISSUE TITLE
Custom mail sender

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#111]
Hi,

It would be great to be able to customize the mail sender in Authelia's YAML configuration file, for notifications.

**Comment by clems4ever** [comment]
This one is easy to implement. Thank you for the request.

**Comment by masau** [comment]
Related: The hard-coded from address currently prevents zoho email (and presumably others) from being used, it returns "553 Relaying disallowed as authelia@authelia.com", so this would be very nice.

**Comment by clems4ever** [comment]
Hello @masau , I will definitely raise the priority of this one. It's easy to fix. I'll keep you posted.

**Comment by clems4ever** [comment]
Hello @masau , @n4kre , I've just merged #137 that allows you to define a sender for both gmail and SMTP notifiers. Please see the configuration template for details. Thanks.
