### ISSUE TITLE
SMTP credentials are logged, even with a log level > debug

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#117]
Hi,

I guess you have forgotten to remove `console.log(smtpOptions);` in `SmtpNotifier.ts`, resulting in the logging of SMTP credentials regardless of the log level.

**Comment by clems4ever** [comment]
I've just made a hotfix. It will be merged in few minutes. Thanks.

**Comment by clems4ever** [comment]
#119 fixes the issue. Thank you for the reporting.
