### ISSUE TITLE
Add “soft“ session timeout

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#123]
Hi,

Currently, Authelia seems to only support “hard” timeout: whatever the user (in)activity, its session expire following the `expiration` parameter provided in Authelia's YAML configuration file.
It would be nice to add an other parameter to support “soft” timeout.

E.g.: whatever happens, the user gets disconnected after the hard timeout (current behavior), *and* also in case it is inactive for some time (soft timeout).

**Comment by clems4ever** [comment]
Hello @n4kre , this is handled in #161
