### ISSUE TITLE
Cookie theft

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#124]
Hi,

As of now, Authelia is likely vulnerable to session cookie theft via XSS – *cf.* [here](https://en.wikipedia.org/wiki/HTTP_cookie#Cross-site_scripting:_cookie_theft).
A simple mitigation would be to set the `HttpOnly` attribute to the session cookie. This can be achieved through the addition of `httpOnly: true` in the cookie option, in `SessionConfigurationBuilder.js`.

**Note**: Ensuring the cookie cannot be sent over an insecure HTTP connection would also be good from a security point of view (`secure: true`) – actually, this it can be a bit tricky due to the fact that Authelia is likely running over HTTP, even though it is behind an HTTPS reverse proxy: the idea is to configure Nginx with `proxy_set_header X-Forwarded-Proto $scheme;` before it forwards the HTTP request to Authelia's backend, and to ask the latter to trust such headers (hopefully, an attacker cannot spoof it, since Nginx will rewrite it, anyway), which you seem to have already implemented.
Then, since the cookie is set to the “base” domain, such [an attack](https://en.wikipedia.org/wiki/HTTP_cookie#Publishing_false_sub-domain:_DNS_cache_poisoning) is possible. I would therefore highly promote in the `README` the use of [HSTS](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/) on *all* subdomains. Anyway, enforcing a strict transport security policy is good practice, not only for that specific reason – however, be careful with it: in the way I recommend to use HSTS, *all* subdomains must implement HTTPS; otherwise they will not be reachable. This would makes the `Secure` cookie attribute a bit useless, but it cannot hurt.

**Comment by n4kre** [comment]
On Authelia login page, I would also recomment the following headers, for security purposes – make sure to read what each of them does:

```nginx
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
add_header Content-Security-Policy "default-src 'self';";
add_header Cache-Control "no-store";
add_header Pragma "no-cache";
```
(Nginx snippet)

**Note**: If you want some “privacy” for your login page, `add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";` is a good idea.

**Comment by n4kre** [comment]
**Important note about my last post**: The `Content-Security-Policy`, as is, prevents Authlia from working; configured in this way, only the content from the same origin should be allowed by the client web browser. You should therefore whitelist in this directive the other origins from the required contents.

**Comment by clems4ever** [comment]
I will definitely try those headers and try to reproduce the issue.
Thank you so much @n4kre.

**Comment by clems4ever** [comment]
Done in #166 and I adapted Authelia to work with Content-Security-Policy :).
