### ISSUE TITLE
userDN hardcoded to CN

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#13]
Lovely piece of software you got here, trying it out right now.

One thing I noticed is you hardcoded the userDN to CN in some places like [here](https://github.com/clems4ever/authelia/blob/0c748e9304cf1905e89e3ec5b4fe368d800c9a73/src/lib/ldap.js#L14), while this might work fine with openldap it does not with [FreeIPA](https://www.freeipa.org/page/Main_Page).

Changeing cn to uid on lines [14](https://github.com/clems4ever/authelia/blob/0c748e9304cf1905e89e3ec5b4fe368d800c9a73/src/lib/ldap.js#L14), [24](https://github.com/clems4ever/authelia/blob/0c748e9304cf1905e89e3ec5b4fe368d800c9a73/src/lib/ldap.js#L24) and [52](https://github.com/clems4ever/authelia/blob/0c748e9304cf1905e89e3ec5b4fe368d800c9a73/src/lib/ldap.js#L52) fixed it for me (only tested with FreeIPA).

**Comment by clems4ever** [comment]
Hello @jkaberg ,

Thank you! That is true, I hardcoded it so that it fitted to my needs and I did not try it with FreeIPA. Do not hesitate to contribute with a PR if your code works and tests are green. I would be glad to review and add your name in the contributors list.

**Comment by jkaberg** [comment]
@clems4ever, PR submitted https://github.com/clems4ever/authelia/pull/15

**Comment by clems4ever** [comment]
@jkaberg, pull request #18 is a long-term solution to what you are trying to do.
