### ISSUE TITLE
Usernames enumeration

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#133]
Hi,

As of now, Authelia's login page respond to failed login attempts with a redish notification stating `Authentication failed. Please double check your credentials.`: this is good.
On the other hand, the HTTP status code that is sent back to the client differs based on whether authentication failed due to non-existing user (`500`) or failed pasword (`401`): an attacker can therefore enumerate valid usenames.

**Note**: f Authelia is responsible for logging login attempts – *cf.* issue #116 –, we don't have to rely on Nginx access logs to get this information, and we can then make Authelia stop responding with HTTP error 5xx or 4xx upon failed login. and simply answer wwith HTTP status 200.

**Comment by n4kre** [comment]
By the way, just wondering: are credentials “sanitized” in some way before getting processed?
I have not dug into it; I was just thinking that they are somehow used in an LDAP query: it would be safer to ensure that the so called query does actually what it is meant to.

**Comment by clems4ever** [comment]
Unfortunately, they are not sanitized and query injection is a possible attack, I guess. What do you recommend to avoid it? Accepting only few characters?
Thanks,
Clément.

**Comment by n4kre** [comment]
I open a new issue, since it is not related to the one from this thread.

**Comment by n4kre** [comment]
To get back to usernames enumeration (well, input sanitization too), the same applies to the password reset page: an HTTP status `500` is sent back to the client upon submission of a non-existing username. The response that is sent back to the client should be identicial regardless the the usename validity: a small notification saying something like “Your request has been sent. If you don't receive any e-mail, check your SPAM folder and make sure you submitted a *valid* username.” (well, it's a bit lengthy, but I'm sure you get the idea) and same HTTP status code.

**Comment by clems4ever** [comment]
For the username enumeration I had in mind to always return 200 (for all requests sent from frontend) with a JSON containing an error message. Error message would be the same when credentials are wrong or user does not exist. Would that be ok?

**Comment by n4kre** [comment]
As explained in my previous post, the point is to give relevant information to the user but without making the slightest distinction between between failed password / non existing username (login attempt) / existing username (password recovery). Hopefully, this only applies to what is sent back to the client – not to what is logged.

**Comment by clems4ever** [comment]
I'm currently reviewing every responses that is sent from Authelia. For authentication and password reset the response will always be 200 (since the service is responding correctly) but there will be an error message in the JSON body and this message will be the same for technical errors (connection problems, bugs) and functional errors (user does not exist, bad authentication). That way, an attacker cannot even tell there is a bug on server side. Less insight from a end user perspective but much more secure.
For unauthorized endpoints the error code will be 401, though.

@n4kre , what do you think of that?

**Comment by n4kre** [comment]
Hello @clems4ever,
For now, I won't have much free time to experiment this, but it sounds indeed very good!

**Comment by clems4ever** [comment]
Should be fixed with #140 . Thanks @n4kre .
