### ISSUE TITLE
LDAP injection

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#134]
Hi,

As suggested in issue #133, Authelia is likely vulnerable to LDAP injection, since inputs are not sanitized – maybe the `ldapjs` module already does it?
*Any* input that can be controled by the users or external parties should be sanitized – easy to say, I guess…

From the [OWASP recommendations](https://www.owasp.org/index.php/LDAP_Injection_Prevention_Cheat_Sheet#Defense_Option_1:_Escape_all_variables_using_the_right_LDAP_encoding_function), one could disallow the following chars to migitate such a risk:
> ',','\','#','+','<','>',';','"','=', and leading or trailing spaces [mathcing the `\s` regex char]

**Note**: For password verification, I *guess* you compute the salted SSHA hash – to be picky, this is not really future-proof: it is a deprecated hash algorithm – from the input password and compare it to the one that is stored in the LDAP server: this input is likely not passed within a LDAP query, so it should not be a problem – for LDAP injection, at least, but some sanitization may be required to prevent some kind of injection straight into Authelia. In the same way, for password modification, I hope the method `dovehash.encode` (in “`lib/ldap/Client.ts`”) does make input sanitization.

**Comment by clems4ever** [comment]
There is definitely something to be done to secure Authelia on this part. I put a high priority.

**Comment by clems4ever** [comment]
Hello @n4kre , #143 should protect against LDAP injection attacks. The sanitizing is done in the component that is sending the requests to the LDAP, the layer wrapping ldapjs. 

For passwords, I need to dig a bit deeper though. I did not want to use SSHA at the beginning but unfortunately SHA-512 was not working with the version of openldap i'm using (don't know why).

I will keep this ticket open until, I'm done with passwords.

**Comment by clems4ever** [comment]
I found a way to use SSHA-512 for storing passwords in the LDAP using crypt. This is a significant security upgrade! :)

**Comment by n4kre** [comment]
Awesome! 👍

**Comment by clems4ever** [comment]
#169 replaces SSHA by SSHA512 in LDAP.

**Comment by clems4ever** [comment]
I still don't really do anything with the incoming password (no sanitization) because I cannot really restrict the input space since Authelia can be one among several access point to the LDAP.
