### ISSUE TITLE
Is it possible to pass through the user credentials for true SSO with back end applications

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#138]
From @jmccoy555: I was wondering if it is / will be possible to pass through the user credentials for true SSO with back end applications, although I think this may require Authelia to support SAML?

**Comment by jmccoy555** [comment]
Hi @clems4ever did you still want me to open on for this (with a bit more detail), or is it closed as you don't think it will be possible? 

Cheers.

**Comment by clems4ever** [comment]
Hello @jmccoy555, I wanted to see if I was able to create a ticket and put you as reporter but I can't. Can you please open a new one?
Thanks.
