### ISSUE TITLE
Add support for SSO credentail pass through

### ISSUE THREAD

**Issue by jmccoy555** [clems4ever/authelia#139]
When Authelia is used to provide 2FA to enhance the security of other web apps it would be nice for the user credentials to be passed through to avoid the user from having to login twice. 

A possible solution for achieving this would be for Authelia and the backend web app to support SAML 2.0, for example;

https://docs.nextcloud.com/server/11/admin_manual/configuration_server/sso_configuration.html

https://sogo.nu/files/docs/SOGoInstallationGuide.html#_authenticating_using_saml2

Regards,

James

**Comment by clems4ever** [comment]
Hello @jmccoy555 , Authelia passes username and groups to apps using **Remote-User** and **Remote-Groups** HTTP headers. Such mechanism is supported in applications like Jenkins for example. 
What's your backend app? Is it home-made?

**Comment by jmccoy555** [comment]
Hi @clems4ever 

For starters I would like to get it working with SOGo. Following your pointer I have discovered that SOGo would appear to support this method;

How to use WebAuth with SOGo? 
When using proxy-side authentication, you must adjust your proxy or front server accordingly and ensure that the "x-webobjects-remote-user" HTTP header is passed to SOGo. With Apache, this is done by using the "RequestHeader" directive in the configuration. The second step is to tell SOGo to trust that value altogether by setting the "SOGoTrustProxyAuthentication" to YES which will disable the login page and the "logoff" link. If the user identifiers that are used do not match their system identifier, for example using Kerberos-based authentication, you need to set the "bindFields" parameter of your authentication LDAP source. This enables SOGo to query your LDAP server for the real user identifier to use during its operations. 

I have set SOGoTrustProxyAuthentication to YES which results in an unauthorized error, progress of sorts!!

My understanding of headers is very limited (Started reading and I have tried a few combinations like proxy_set_header Remote-User $user;), would you be able to give me an example?

My set up is Web > Nginx > auth_request in location block > Authelia > Nginx proxy pass > SOGo Apache server with RequestHeader set "x-webobjects-remote-user" "%{REMOTE_USER}e" env=REMOTE_USER 

Thanks!!

**Comment by jmccoy555** [comment]
A bit more investigating. If I set the header to my username manually then I can log in through Authelia;

proxy_set_header x-webobjects-remote-user james;

But this will obviously log every user in as me!! So it looks like the issue I'm facing is how to get the username back from Autherlia into the header.

Has this always been implemented, or maybe I need to update to the latest version? 

Thanks.

**Comment by clems4ever** [comment]
Hello @jmccoy555 , look at how it's done in the example/nginx/nginx.conf
I retrieve the username from Authelia by reading **$upstream_http_remote_user** and transform it before sending it to the backend with the following two lines:
```
auth_request_set $user $upstream_http_remote_user;
proxy_set_header X-Forwarded-User $user;
```
Replace **X-Forwarded-User** with your own header and it should work.

**Comment by jmccoy555** [comment]
Hi @clems4ever thanks for you reply. I'm half glad you said this as it would appear logical, and something I have tried, but no luck with;

        auth_request_set $user $upstream_http_remote_user;
        proxy_set_header x-webobjects-remote-user $user;

Just double check I tried;

        auth_request_set $user james;
        proxy_set_header x-webobjects-remote-user $user;

and that obviously logs me in as james.

I presume this is the same username that you log into Authelia with and nothing else is added?

**Comment by clems4ever** [comment]
Hello @jmccoy555, I will try to reproduce on master and see if there is a bug. Unfortunately, this feature has not been very much tested so far. I'll keep you posted in few minutes.

**Comment by jmccoy555** [comment]
Super, thanks @clems4ever 

I have discovered the way SOGo works is that if it is given the header then it tries to use it to authenticate, if successful it logs you in, if not you get an unauthrosied screen. If no header is passed then it takes you to the usual SOGo login screen. 

As before if I set the header to my name, I get logged in (well sort of IMAP moans about a password issue, but that's next to investigate). If I set the header with some random letters, I get unauthroised as expected.

If I set the header as above trying to pass through form Authelia, then I get the normal SOGo login screen which would suggest that nothing is getting passed through.

**Comment by clems4ever** [comment]
Ok, everything is clear now. Thanks for the investigation!
I'm currently adding an integration test for this use case and I'll see how it goes.

**Comment by clems4ever** [comment]
@jmccoy555 , unfortunately it seems to work at head... I plugged httpbin (https://httpbin.org/) as a protected backend and use **/headers** endpoint to check what were the headers and they seem to be correctly filled with username and groups.

What version of Authelia are you using?

**Comment by clems4ever** [comment]
Can you please post your nginx config?

**Comment by jmccoy555** [comment]
Thanks for trying. I'm using a docker version from a couple of weeks ago, before the ACL and other new features got implemented. I haven't had time to update my config to try with a newer version. I was hoping to try this weekend.

Anyway, here's my nginx config.

 server
   {
        listen     443 ssl;
        server_name mail.my.domain;
        
        ssl_certificate /path_to_my/fullchain.pem;
        ssl_certificate_key /path_to_my/privkey.pem;

    location /auth_verify {
        internal;
        proxy_set_header  X-Original-URI $request_uri;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  Host $http_host;
        proxy_set_header  Content-Length "";

        proxy_pass        http://10.10.1.103:80/verify;

        }

      
      location ^~/SOGo {

        auth_request /auth_verify;
        
        auth_request_set $redirect $upstream_http_redirect;
        proxy_set_header Redirect $redirect;

        auth_request_set $user $upstream_http_remote_user;
        proxy_set_header x-webobjects-remote-user $user;
            
        auth_request_set $groups $upstream_http_remote_groups;
        proxy_set_header Remote-Groups $groups;

         proxy_pass http://10.10.1.105:20000; 
         proxy_redirect `http://10.10.10.105:20000` default; 
         # forward user's IP address 
         proxy_set_header X-Real-IP $remote_addr; 
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
         proxy_set_header Host $host; 
         proxy_set_header x-webobjects-server-protocol HTTP/1.0; 
         proxy_set_header x-webobjects-remote-host 127.0.0.1; 
         proxy_set_header x-webobjects-server-name $server_name; 
         proxy_set_header x-webobjects-server-url $scheme://$host; 
         proxy_set_header x-webobjects-server-port $server_port; 
         proxy_connect_timeout 90;
         proxy_send_timeout 90;
         proxy_read_timeout 90;
         proxy_buffer_size 4k;
         proxy_buffers 4 32k;
         proxy_busy_buffers_size 64k;
         proxy_temp_file_write_size 64k;
         client_max_body_size 50m;
         client_body_buffer_size 128k;
         
	 break;
      }
      
}

I can try with httpbin if you can point me in the right direction.

**Comment by clems4ever** [comment]
LGTM. Can you post Authelia's logs?

If you want to try with httpbin, you just have to use **citizenstig/httpbin** docker image and copy your SOGo block and replace 
`location ^~/SOGo {` by `location /headers {`
and
`proxy_pass http://10.10.1.105:20000;` by `proxy_pass http://<name_of_http_bin_service or IP>:8000/headers;`

Note: make sure your httpbin container is in the same virtual network as nginx.

And normally you should be able to GET **/headers** which should gives you the exhaustive list of headers passed to your app.

**Comment by jmccoy555** [comment]
I'll give that a try.

In the mean time here's the log. I restarted and then tried to log in once.

Parse configuration file: /etc/authelia/config.yml
Log level =  debug
debug: Content of YAML configuration file is {
  "port": 80,
  "logs_level": "debug",
  "ldap": {
    "url": "ldap://10.10.1.101:389",
    "base_dn": "dc=domain,dc=lan",
    "additional_users_dn": "cn=users",
    "users_filter": "sAMAccountName={0}",
    "additional_groups_dn": "cn=groups",
    "groups_filter": "(&(member={0})(objectclass=group))",
    "group_name_attribute": "cn",
    "mail_attribute": "mail",
    "user": "cn=administrator,cn=users,dc=domain,dc=lan",
    "password": "xxxxxx"
  },
  "access_control": {
    "default": [
      "my.domain"
    ],
    "groups": {
      "domain_users": [
        "mail.my.domain"
      ]
    },
    "users": null
  },
  "session": {
    "secret": "unsecure_secret",
    "expiration": 3600000,
    "domain": "my.domain",
    "redis": {
      "host": "redis",
      "port": 6379
    }
  },
  "regulation": {
    "max_retries": 3,
    "find_time": 120,
    "ban_time": 300
  },
  "storage": {
    "mongo": {
      "url": "mongodb://mongo/authelia"
    }
  },
  "notifier": {
    "gmail": {
      "username": "xxxxxxn@gmail.com",
      "password": "xxxxxxx"
    }
  }
}
debug: Authelia configuration is {
  "port": 80,
  "ldap": {
    "url": "ldap://10.10.1.101:389",
    "users_dn": "cn=users,dc=domain,dc=lan",
    "users_filter": "sAMAccountName={0}",
    "groups_dn": "cn=groups,dc=domain,dc=lan",
    "groups_filter": "(&(member={0})(objectclass=group))",
    "group_name_attribute": "cn",
    "mail_attribute": "mail",
    "password": "xxxxxx",
    "user": "cn=administrator,cn=users,dc=domain,dc=lan"
  },
  "session": {
    "domain": "my.domain",
    "secret": "unsecure_secret",
    "expiration": 3600000,
    "redis": {
      "host": "redis",
      "port": 6379
    }
  },
  "storage": {
    "mongo": {
      "url": "mongodb://mongo/authelia"
    }
  },
  "logs_level": "debug",
  "notifier": {
    "gmail": {
      "username": "xxxxx@gmail.com",
      "password": "xxxxxxx"
    }
  },
  "access_control": {
    "default": [
      "my.domain"
    ],
    "groups": {
      "domain_users": [
        "mail.my.domain"
      ]
    },
    "users": null
  },
  "regulation": {
    "max_retries": 3,
    "find_time": 120,
    "ban_time": 300
  }
}
Listening on 80...
The server is started!
debug: Verify: headers are {"x-original-uri":"/SOGo","x-real-ip":"10.10.1.53","host":"mail.my.domain","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://my.domain/","dnt":"1","upgrade-insecure-requests":"1"}
error: Reply with error 401: FirstFactorValidationError: First factor has not been validated yet.
debug: First factor: headers are {"x-original-uri":"/?redirect=https%3A%2F%2Fmail.my.domain%2FSOGo","host":"auth.my.domain","x-real-ip":"10.10.1.53","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://my.domain/","dnt":"1","upgrade-insecure-requests":"1"}
info: 1st factor: Starting authentication of user "james"
debug: 1st factor: Start bind operation against LDAP
debug: 1st factor: username=james
info: 1st factor: No regulation applied.
debug: LDAP: Bind user 'cn=administrator,cn=users,dc=domain,dc=lan'
debug: LDAP: searching for user dn of james
debug: LDAP: Search for '{"scope":"sub","sizeLimit":1,"attributes":["dn"],"filter":"sAMAccountName=james"}' in 'cn=users,dc=domain,dc=lan'
debug: Entry retrieved from LDAP is '{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[]}'
debug: LDAP: Search ended and results are '[{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[]}]'.
debug: LDAP: retrieved user dn is CN=James,CN=Users,DC=domain,DC=lan
debug: LDAP: Bind user 'CN=James,CN=Users,DC=domain,DC=lan'
debug: LDAP: Unbind user 'CN=James,CN=Users,DC=domain,DC=lan'
debug: LDAP: Bind user 'cn=administrator,cn=users,dc=domain,dc=lan'
debug: LDAP: searching for user dn of james
debug: LDAP: Search for '{"scope":"sub","sizeLimit":1,"attributes":["dn"],"filter":"sAMAccountName=james"}' in 'cn=users,dc=domain,dc=lan'
debug: Entry retrieved from LDAP is '{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[]}'
debug: LDAP: Search ended and results are '[{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[]}]'.
debug: LDAP: retrieved user dn is CN=James,CN=Users,DC=domain,DC=lan
debug: LDAP: Search for '{"scope":"base","sizeLimit":1,"attributes":["mail"]}' in 'CN=James,CN=Users,DC=domain,DC=lan'
debug: Entry retrieved from LDAP is '{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[],"mail":"james@domain.email"}'
debug: LDAP: Search ended and results are '[{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[],"mail":"james@domain.email"}]'.
debug: LDAP: emails of user 'james' are james@domain.email
debug: LDAP: searching for user dn of james
debug: LDAP: Search for '{"scope":"sub","sizeLimit":1,"attributes":["dn"],"filter":"sAMAccountName=james"}' in 'cn=users,dc=domain,dc=lan'
debug: Entry retrieved from LDAP is '{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[]}'
debug: LDAP: Search ended and results are '[{"dn":"CN=James,CN=Users,DC=domain,DC=lan","controls":[]}]'.
debug: LDAP: retrieved user dn is CN=James,CN=Users,DC=domain,DC=lan
debug: LDAP: Search for '{"scope":"sub","attributes":["cn"],"filter":"(&(member=CN=James,CN=Users,DC=domain,DC=lan)(objectclass=group))"}' in 'cn=groups,dc=domain,dc=lan'
debug: Entry retrieved from LDAP is '{"dn":"CN=domain_users,CN=Groups,DC=domain,DC=lan","controls":[],"cn":"domain_users"}'
debug: LDAP: Search ended and results are '[{"dn":"CN=domain_users,CN=Groups,DC=domain,DC=lan","controls":[],"cn":"domain_users"}]'.
debug: LDAP: groups of user james are domain_users
debug: LDAP: Unbind user 'cn=administrator,cn=users,dc=domain,dc=lan'
info: 1st factor: LDAP binding successful. Retrieved information about user are {"emails":["james@domain.email"],"groups":["domain_users"]}
debug: 1st factor: Mark successful authentication to regulator.
debug: AuthSession is {"first_factor":true,"second_factor":false,"groups":["domain_users"],"userid":"james","email":"james@domain.email"}
debug: AuthSession is {"first_factor":true,"second_factor":false,"groups":["domain_users"],"userid":"james","email":"james@domain.email"}
info: POST 2ndfactor totp: Initiate TOTP validation for user james
debug: POST 2ndfactor totp: Fetching secret for user james
debug: POST 2ndfactor totp: TOTP secret is {"_id":"59c64ac5b9a67d5601224831","userId":"james","secret":{"ascii":"r<l!4[%ZsI*>BUR%n>dp8sH1h#5KFk#P","hex":"723c6c21345b255a73492a3e425552256e3e6470387348316823354b466b2350","base32":"OI6GYIJULMSVU42JFI7EEVKSEVXD4ZDQHBZUQMLIEM2UWRTLENIA","otpauth_url":"otpauth://totp/SecretKey?secret=OI6GYIJULMSVU42JFI7EEVKSEVXD4ZDQHBZUQMLIEM2UWRTLENIA"}}
debug: POST 2ndfactor totp: TOTP validation succeeded
debug: Verify: headers are {"x-original-uri":"/SOGo","x-real-ip":"10.10.1.53","host":"mail.my.domain","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://auth.my.domain/secondfactor?redirect=https%3A%2F%2Fmail.my.domain%2FSOGo","cookie":"connect.sid=s%3Ao_XgBblnyopuSKwlko1rWGOibSBdRJnz.8UZwwXdvcc3WGbDaWgRh1ekkS%2FEDysx%2FkCBnsEVJLU4","dnt":"1","upgrade-insecure-requests":"1"}
mail.my.domain
debug: ACL: user 'james' is allowed access to ["my.domain","mail.my.domain"]
debug: ACL: trying to match mail.my.domain with ["my.domain","mail.my.domain"]
debug: Verify: headers are {"x-original-uri":"/SOGo/","x-real-ip":"10.10.1.53","host":"mail.my.domain","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://auth.my.domain/secondfactor?redirect=https%3A%2F%2Fmail.my.domain%2FSOGo","cookie":"connect.sid=s%3Ao_XgBblnyopuSKwlko1rWGOibSBdRJnz.8UZwwXdvcc3WGbDaWgRh1ekkS%2FEDysx%2FkCBnsEVJLU4","dnt":"1","upgrade-insecure-requests":"1"}
mail.my.domain
debug: ACL: user 'james' is allowed access to ["my.domain","mail.my.domain"]
debug: ACL: trying to match mail.my.domain with ["my.domain","mail.my.domain"]

**Comment by jmccoy555** [comment]
Checked headers;


with
        auth_request_set $user $upstream_http_remote_user;
        proxy_set_header x-webobjects-remote-user $user;
        
        

{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en-US,en;q=0.5", 
    "Cache-Control": "max-age=0", 
    "Connection": "close", 
    "Cookie": "connect.sid=s%3A0PyfGeLwhB23ICZknKTCo6dfJFSkN1Ec.KeSiBcVuIoIN9ZVtZCKWN7s7Fjw5gITLrXuInfqcxg0", 
    "Dnt": "1", 
    "Host": "mail.my.domain", 
    "Redirect": "https%3A%2F%2Fmail.my.domain%2Fheaders", 
    "Referer": "https://auth.my.domain/secondfactor?redirect=https%3A%2F%2Fmail.my.domain%2Fheaders", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0", 
    "X-Webobjects-Server-Name": "mail.my.domain", 
    "X-Webobjects-Server-Port": "443", 
    "X-Webobjects-Server-Protocol": "HTTP/1.0", 
    "X-Webobjects-Server-Url": "https://mail.my.domain"
  }
}



with 

        auth_request_set $user $upstream_http_remote_user;
        proxy_set_header x-webobjects-remote-user james;


{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en-US,en;q=0.5", 
    "Cache-Control": "max-age=0", 
    "Connection": "close", 
    "Cookie": "connect.sid=s%3A0PyfGeLwhB23ICZknKTCo6dfJFSkN1Ec.KeSiBcVuIoIN9ZVtZCKWN7s7Fjw5gITLrXuInfqcxg0", 
    "Dnt": "1", 
    "Host": "mail.my.domain", 
    "Redirect": "https%3A%2F%2Fmail.my.domain%2Fheaders", 
    "Referer": "https://auth.my.domain/secondfactor?redirect=https%3A%2F%2Fmail.my.domain%2Fheaders", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0", 
    "X-Webobjects-Remote-User": "james", 
    "X-Webobjects-Server-Name": "mail.my.domain", 
    "X-Webobjects-Server-Port": "443", 
    "X-Webobjects-Server-Protocol": "HTTP/1.0", 
    "X-Webobjects-Server-Url": "https://mail.my.domain"
  }
}


So it look's like I need to update Authelia and try again?

**Comment by jmccoy555** [comment]
Updated to v3.5.0 and now Authelia is passing thought the header, but my group membership is no longer working - debug: LDAP: groups of user james are

But I can close this one, unless you'd like any more info?

**Comment by clems4ever** [comment]
Hello @jmccoy555 , that's great! 

Can you please publish your new configuration? It's likely to be due to LDAP configuration since, it has changed lately. Some users wanted to have something more customizable for supporting their LDAP architecture.

**Comment by jmccoy555** [comment]
Hi @clems4ever thanks for all your help.

Looking at #106 I think you're right.

I setup Zentyal (a long time ago, kind of regretting it these days) as my LDAP server. When you add a user you specify a username, which is assigned as the sAMAccountName and user part of the email, and also Firstname and Surname which it then combines to make the user cn = Firstname Surname, resulting in a dn of cn=Firstname Surname,cn=users,dc=example,dc=com. 

Previously setting users_filter: sAMAccountName={0} was fine as Authelia pulled through the full user dn to query the group membership with groups_filter: (&(member={0})(objectclass=group))

However this change has resulted in the group membership query effectively being cn=sAMAccountName,cn=users,dc=example,dc=com returning no results rather than cn=Firstname Surname,cn=users,dc=example,dc=com as expected by my LDAP server. 

Any ideas how I can resolve this? 


Previous config
ldap:
  # The url of the ldap server
  url: ldap://10.10.1.101:389

  # The base dn for every entries
  base_dn: dc=example,dc=com

  # An additional dn to define the scope to all users
  additional_users_dn: cn=users

  # The users filter. 
  # {0} is the matcher replaced by username.
  # 'cn={0}' by default.
  users_filter: sAMAccountName={0}

  # An additional dn to define the scope of groups
  additional_groups_dn: cn=groups
  
  # The groups filter.
  # {0} is the matcher replaced by user dn.
  # 'member={0}' by default.
  groups_filter: (&(member={0})(objectclass=group))
  
  # The attribute holding the name of the group
  group_name_attribute: cn

  # The attribute holding the mail address of the user
  mail_attribute: mail

  # The username and password of the admin user.
  user: cn=administrator,cn=users,dc=example,dc=com
  password: xxxxxxx

**Comment by clems4ever** [comment]
Ok, I see the issue. You should replace your **groups_filter** with the following:
`groups_filter: (&(member=cn={0},ou=users,dc=example,dc=com)(objectclass=groupOfNames))`.

`{0}` is now replaced by username instead of user DN. Indeed, this was blocking for a user at some point because he had an attribute set to username instead of user DN. And since user DN can be rebuilt from username, I decided to make the change.

**Comment by jmccoy555** [comment]
No luck unfortunately. Authelia does look to be retrieving the full and correct dn though. The logs look quite different between the two versions, although I suspect that's because of changes to Authelia. 

Shall I open a new issue or add to #106?

**Comment by clems4ever** [comment]
Hello @jmccoy555 , it took me some time to understand the issue but I think I got it now. Given your current organization in the LDAP, Authelia is not able to compute the user DN from the username only to retrieve the groups, correct? If so, please create a new ticket since #106 is already merged.

FYI, the logs indeed changed a lot between the two versions because I wanted to improve tracking users and sessions overtime. It was painful before...
