### ISSUE TITLE
No available notifier option detected

### ISSUE THREAD

**Issue by Ellipsiss** [clems4ever/authelia#141]
Hi there

I have just tried to install / run authelia in docker. It seems to be loading my config file fine (as it shows in the logs) but then this error occurs when starting

```
}'
/usr/src/server/src/lib/notifiers/NotifierFactory.js:16
            throw new Error("No available notifier option detected.");
            ^

Error: No available notifier option detected.
    at Function.build (/usr/src/server/src/lib/notifiers/NotifierFactory.js:16:19)
    at Function.initialize (/usr/src/server/src/lib/ServerVariablesHandler.js:45:60)
    at Server.setup (/usr/src/server/src/lib/Server.js:62:64)
    at Server.start (/usr/src/server/src/lib/Server.js:79:21)
    at Object.<anonymous> (/usr/src/server/src/index.js:25:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

/usr/src/node_modules/yamljs/lib/Parser.js:347
        throw new ParseException('Indentation problem.', this.getRealCurrentLineNb() + 1, this.currentLine);

^
Error: Indentation problem.
```

Any idea how to solve this? Thanks!

**Comment by clems4ever** [comment]
Hello @Ellipsiss, as stated in the stack trace, your problem seems to be a malformed config file. Can you gist it?

**Comment by Ellipsiss** [comment]
Sure thing. Thanks for replying so quickly

https://pastebin.com/YPcmEx1z

**Comment by clems4ever** [comment]
@Ellipsiss , I see two problems at first glance.
1/ you enabled two notifiers while only one will be used. I will clarify the usage in the config.template.yml.
2/ Your yaml is malformed. There are 3 spaces at the beginning of **gmail** object and 2 at the beginning of the **filesystem** object. This lack of consistency explains why you had the **"Indentation problem"** error message.

**Comment by clems4ever** [comment]
Hello @Ellipsiss , have you solved your issue?

**Comment by Ellipsiss** [comment]
Hi @clems4ever. Sorry for the delay. Yes I did. At first I was just using the filesystem - it didnt work so I then added gmail too. Like you said this would have sprung the issue. I removed the spaces and also changed to just using Gmail.

I know this doesn't relate to my original issue - but it appears that I have it all working and I think the LDAP authentication is working.

How do I then configure my subdomains to authenticate through authelia? I have tried to look through the config file to no avail. I'm using NGINX as a reverse proxy with basic_auth right now.

**Comment by clems4ever** [comment]
Hello @Ellipsiss , from 3.6.0 you will be able to use basic_auth with Authelia and NGINX.

Since the initial problem has been solved, I'm closing this ticket. Can you please insert new issues for bugs or questions you might have?
If you just need some help to set up Authelia we can definitely talk in Gitter (or Slack, I can setup one if it's more convenient for you).
