### ISSUE TITLE
Indicate browser incompatibility with U2F

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#145]
Hi @clems4ever,

For an improved U2F user-experience – well, it's about the economy of single click; but most users are reluctant to 2FA because “it's an extra step I'll have to do every time I wanna log in, I hate security guys, they're p*ssing me off”, and that's why I think it's important for Authelia to be as user-friendly as possible –, do you think it would be possible to have a unified second factor authentication page – for both TOTP and U2F?

I mean, something like this:

<img width="540" alt="ux" src="https://user-images.githubusercontent.com/14371127/31581212-9b667ad8-b133-11e7-8b4c-580deb0772b4.png">

That way, a U2F user wouldn't have to hit the “U2F” button. What's more, there is no longer two “Need to register?”: I think this is more “natural”.

What's more, I guess most users simply do not know what TOTP means – and don't have to. This is why I think “TOTP” should always be referred as “one-time password” and tightly linked to Google Authenticator – “Where do I get such one-time passwords?”.

For instance, the TOTP registration page could look like this:

<img width="715" alt="reg_totp" src="https://user-images.githubusercontent.com/14371127/31581205-3b9e21d2-b133-11e7-99b5-b80618518b54.png">

(In the same way, the TOTP registration e-mail title and body shouldn't directly mention “TOTP secret key”.)

What's your opinion about it?

**Comment by clems4ever** [comment]
I love your mockups! Particularly the 2 icons to get Google Authenticator, that's awesome.

For the UX, you are right, faster is better. Not requiring the user to click anywhere before authenticating is hopefully a good thing. 

At some point I had in mind to give the user a way to define his preferred authentication method so that when he arrives on the second factor page this method is used by default and the other still accessible by using a link at the bottom to switch. But this is a bit more complicated to implement so I will go with your proposal and see how it goes first.

**Comment by n4kre** [comment]
By the way, two more details:
- In the U2F registration e-mail, it would be cool to tell the user to open the link with a U2F-enabled web browser – *cf.* [here](https://www.yubico.com/support/knowledge-base/categories/articles/browsers-support-u2f/) – otherwise U2F cannot be used. In my case, Safari is my default web browser, and I have to pay attention to this. One may recommend to dynamically adapt Authelia's behavior to the `User-Agent`, but I think it would not be very sustainable.
- Same remark for failure notifications related to U2F – maybe add something like “[Make sure your web browser supports U2F.](https://www.yubico.com/support/knowledge-base/categories/articles/browsers-support-u2f/)”.

**Comment by jmccoy555** [comment]
Having now got a U2F key to play around with, I think this would be great. 

I keep logging in the first factor, moving my hand from my mouse to press my key, to remember that I need to click first.

The little note about browser compatibility would be a good idea too, having wondered why Firefox wouldn't work for a few minuets!!! Although the new version out soon should I believe.

**Comment by clems4ever** [comment]
@jmccoy555 , thank  you for the feedback, especially on Firefox. I will try to do something about it.

**Comment by clems4ever** [comment]
This is treated in the latest version of Authelia. The U2F option is not displayed in the case the browser does not support U2F.
