### ISSUE TITLE
Authelia can not build a user's distinguised name

### ISSUE THREAD

**Issue by jmccoy555** [clems4ever/authelia#146]
Hi @clems4ever 

Since implementing the new group filter whereby Authelia now attempts to build a user's distinguished name from parts there is an issue when a user's username is not a component of their distinguished name.

e.g. user Joe has a username joe and a cn of Joe Blogs, resulting in a dn of cn=Joe Blogs,ou=users,dc=example,dc=com

When Joe logs in to Authelia with his username joe she builds his dn resulting in cn=joe,ou=users,dc=example,dc=com which is there queried against the LDAP server for group membership. However this fails as this dn is not recognised. 

After a bit of googling it would appear that some say the cn must be unique, others use it as the full firstname lastname as in this case; instead relying on another attribute like the sAMAccountName to be the unique identifier for a given domain (as in my use case). 

I'm ready for some testing and helping in any way I can!!!

Cheers.

**Comment by clems4ever** [comment]
Hello @jmccoy555 , I will provide you with a fix in few minutes. Thank you so much again for the time you spent before finding the issue! I'll keep you posted.

**Comment by jmccoy555** [comment]
All fixed. Thanks :)

**Comment by clems4ever** [comment]
Hello @jmccoy555 , my release model was not very good so far. I wanted to do a one-off version only containing the fix you need but given what I have now I need to create a new **release** branch for this specific patch. I would like to avoid that to not have plenty of release branches. Do you mind if I release your fix with the latest fixes already in master (the configuration might break, but not by much).

From now on, I will use 'develop' branch to add features and do MRs and use master only for releasing only.

**Comment by clems4ever** [comment]
On which branch are you? master?

**Comment by jmccoy555** [comment]
Yes, just pulled the docker image with master tag, about an hour since last build. 

Will this go to a specific version soon?

**Comment by clems4ever** [comment]
I've almost forgot I've done the fix to publish the master tag in dockerhub, great! 

Yes, it will go into a 3.6.0 very soon but as I said Authelia will then be expecting some new attributes in configuration and since I added a configuration validator at startup, old configuration might need to be updated but it's really not a big deal. I think it will only be a matter of adding `sender` to Gmail and SMTP notifier.

**Comment by clems4ever** [comment]
But compared to previous versions, the validator will tell you what's wrong in the configuration.

**Comment by jmccoy555** [comment]
Yes, just the sender had to be added.
