### ISSUE TITLE
Use SMTP notifier without username and password

### ISSUE THREAD

**Issue by jmccoy555** [clems4ever/authelia#150]
Hi @clems4ever (sorry for keeping you busy!!)

My SMTP server does not require a username or password, however if left black Authelia will not start. 

If the username and password fields are commented out, Authelia also fails to start. 

Can this option be added please?

**Comment by clems4ever** [comment]
Hello @jmccoy555, indeed I did not handle this use case before. Yes, it can be added for sure.

**Comment by jmccoy555** [comment]
Hi @clems4ever 

Just pulled the develop docker image and this is working nicely!!

Thanks.

**Comment by clems4ever** [comment]
That's awesome! Thank you for testing!
