### ISSUE TITLE
'per_subdomain_methods' should be optional

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#151]
Hi,

As of now, in Authelia's configuration file, `per_subdomain_methods` seems to me mandatory.
I guess it should be optional.

**Comment by clems4ever** [comment]
@n4kre , yes I can make it optional.

**Comment by n4kre** [comment]
Thanks! 👍 

(By the way, #108 should be re-opened, I guess – not sure whether you get a notification for new posts in a “closed” issue.)

**Comment by clems4ever** [comment]
#153 should make it optional.

**Comment by clems4ever** [comment]
Yes, I see them in my mailbox.
