### ISSUE TITLE
"Already logged in" page should be protected when user is not authenticated

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#154]

**Comment by n4kre** [comment]
Hi @clems4ever,

There might also be a little bug, as described in #108. Have you been able to reproduce?

It would also be cool to replace
> You are already logged in.

with something like

> You are already logged in as **username**.

(Just like you have already implemented in the second factor authentication page.)

This may be relevant for the end user to know under which identity it is logged in – e.g., the user has multiple accounts, with different permissions.

**Comment by clems4ever** [comment]
The page is now protected ( #155 ). I will add the username to the page as you suggest.

**Comment by n4kre** [comment]
Thank you :)

**Comment by clems4ever** [comment]
#157 added username to the 'already logged in' page.
