### ISSUE TITLE
`grunt build-dist` fails during grunt-browserify

### ISSUE THREAD

**Issue by khimaros** [clems4ever/authelia#173]
I'm seeing this issue with `master` and `develop` branches. This seems to be a relatively recent regression.

```
Running "browserify:dist" (browserify) task
>> Error: Cannot find module 'bluebird' from '/var/build/depot/ldap/authelia/dist/client/src/lib/firstfactor'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

With `grunt --force`, it fails for another reason:

```
Running "browserify:dist" (browserify) task
>> Error: Cannot find module 'bluebird' from '/var/build/depot/ldap/authelia/dist/client/src/lib/firstfactor'
Warning: Error running grunt-browserify. Used --force, continuing.
>> Error: Cannot find module 'bluebird' from '/var/build/depot/ldap/authelia/dist/client/src/lib/u2f-register'
Warning: Error running grunt-browserify. Used --force, continuing.
Fatal error: Callback was already called.
```

**Comment by clems4ever** [comment]
Hello @khimaros , I guess npm dependencies are not resolved correctly on your workstation. #174 should fix this issue. I've just committed my **package-lock.json** since the build works on my machine.

**Comment by clems4ever** [comment]
As mentioned in #174 , this issue seems to be due to bluebird not being defined as a dev dependency.
The deployment command given in the README (`npm install --only=dev`) is supposed to be tested during integration test phase but the test seems to be incorrect... I will fix it soon. 

Thank you for the report.

**Comment by clems4ever** [comment]
#177 should fix the issue.
