### ISSUE TITLE
Access control “any” group with policy “allow” should not even require authentication

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#184]
Hi,

Here is the objective:
- https://private.example.com should be protected with Authelia.
- Nevertheless, https://private.example.com/someStringThatCanBeRegexed should be publicly accessible, without even requiring to authenticate (a client API needs access to it).

As of now, I have to tweak my Nginx configuration to achieve the desired behavior.
It would be more natural to configure Nginx so that the whole (sub)domain is protected with Authelia, and to configure the whole access control only with Authelia. To do so, it would require Authelia's access control for `any` group with an `allow` policy to be directly authorized (no redirection at all).
After all, such an access control means “totally public”, right?

Does it make sense to you? Do I forget something in this rationale?

**Comment by clems4ever** [comment]
Hello @n4kre, this example does make sense but I would definitely go for the proxy configuration anyway to avoid the round trip to the authentication server for that resource. You see what I mean?

**Comment by n4kre** [comment]
Hi @clems4ever,

I get your point, it it better not to even go through Authelia. On top of that, in case we want to specifically deny access for some group (override the `any` group access control policy), it is important to keep it in the way it currently is. Thank you!

**Comment by clems4ever** [comment]
Great. I'm closing the issue then. Thank you!
