### ISSUE TITLE
About default redirection

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#190]
Hi @clems4ever,

Two little concerns about the default redirection:
- Since it is an optional parameter; is not set, the “already logged in” page should not display “If you are not redirected in few seconds, click here.” in case is has not been configured.
- May be this parameter should be set in the ACL section of the configuration file: e.g., by default, anyone is redirected to some page, while user “admin” is redirected to some administrative page, members of group ”customers” are redirected elsewhere, etc.

What do you think about it?

**Comment by clems4ever** [comment]
Hello @n4kre ,

* you are right, I fixed it few minutes ago when redirecting users facing a 401 or 403. I will do the same for the "already logged in" page.
* This is a good idea indeed. I won't mix it with ACLs though but perhaps add a new section for this matter.

Can you please split this in two separate tickets so that I can prioritize them separately?

**Comment by n4kre** [comment]
Great!

Yes, of course: the is not an ACL *per se*, but you got my point: to have it tied to the groups/users.

**Comment by n4kre** [comment]
I have noticed other things:
- If the user authenticate through U2F rather than TOTP, he does not get any notification upon successful (or failed, I guess) login.
- If the default redirection is not configured, the user is is not redirected to the `/loggedin`. He stays on the second factor page: a bit confusing. I guess it should be redirected to `/loggedin`.
- If the default redirection page is protected only with single factor authentication, the user should then not be prompted for the second factor authentication.

In case you actually decide to tie the default redirection to the user/group (like ACLs), then here is what could be done to deal with it:
- Make sure failed login attempts trigger a notification pop-up, (both for 1st and 2nd factor and U2F and TOTP)
- Remove notification pop-ups related to successful authentication and. Instead, redirect to `/secondfactor` after 1st factor authentication (or to `/loggedin` in case the default redirection is made to a page not requiring 2FA) and to `/loggedin` after second factor authentication (if appropriate).
- Make `/loggedin` dynamic:
   - Add “You can complete second factor authentication here.” if user has not done so yet.
   - Remove “If you are not redirected in few seconds, click here.” in case there is no default redirection page. Else, actually redirect the user to its default redirection page (current behavior).
   - Remove “already” from “You are already logged in as afavre.” in any case—weird to see it in case you have just logged in, and not necessary otherwise.
- Make the redirection delay configurable in Authelia's config (globally).

**Comment by clems4ever** [comment]
Hello @n4kre , thank you for the report. There are a lot of things in the last comment. Can you please file new tickets for each issue so that it is easier for everybody to follow?

**Comment by n4kre** [comment]
Hi @clems4ever,

Considering this ticket was merely about
> Since [default redirection] is an optional parameter; is not set, the “already logged in” page should not display “If you are not redirected in few seconds, click here.” in case is has not been configured.
I think it can be closed now: you have solved it.

With regard to tying the default redirection to the user in the same way as ACLs, I have opened a dedicated ticket, following your advice. See #200.
