### ISSUE TITLE
U2F registration final redirection

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#191]
Hi,

In case I want to register a U2F token, I get redirected to `/secondfactor/u2f/identity/undefined` (giving an error 404) in the end of the registration process.

**Comment by n4kre** [comment]
I cannot reproduce it anymore—I have updated Authelia and my Nginx config, so I do not know which on was faulty. Anyway, it is no longer an issue.

**Comment by clems4ever** [comment]
hello @n4kre, this is expected. It was fixed in #194.
