### ISSUE TITLE
Error 401 and 403 redirections

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#192]
Hi,

Getting back on #167, here is a scenario giving a weird behavior:
- User is not logged in and visit some page requiring authentication on `https://login.example.com` (Authelia's web UI itself), say `https://login.example.com/loggedin`, for instance.
- Then, the user gets a 401 error: perfectly normal. However, it also states “Please click here if you are not redirected in few seconds.”, with a link pointing to the default redirection page—not the original requested URI—, to where it gets redirected. If there is no default redirection in Authelia's config, there a is merely the 401 error, of course.

This exact same behavior occurs for a lack of autorisation, but with 403 instead of 401, when an authenticated user try to access a resource protected by Authelia (not necessarily on Authelia's web UI itself) and does not have sufficient rights.

In both cases, I guess this should be totally unrelated to the default redirection page: maybe both Authelia's 401 and 403 pages should include something like:

> Please log in with an account having sufficient permissions to access this resource.
>
> Click here if you are not redirected in few seconds.

where “here” refers to `https://login.example.com/?redirect=originalRequestedURI` (with automatic redirection, of course).

Hopefully, as already implemented in Authelia, unauthenticated users won't have to go through Authelia's 40x page (and thus wait for a couple of seconds) in case they try to access a resource that is protected by Authelia: only authenticated but unauthorized ones will land on such a page.

**Comment by clems4ever** [comment]
I think this feature is already handled at head.

The error 403 page comes with the following message:
> You don't have enough privileges to access this resource.
> Please click here if you are not redirected in few seconds.

And 401 with:
> You are not authorized to access this resource.<br/><br/>
> Please click here if you are not redirected in few seconds.

The second sentence disappears if there is no link to redirect to. Can you please try and tell me if you see something missing from what you expect?

**Comment by clems4ever** [comment]
The "already logged in" page will be handled in #194 .

**Comment by clems4ever** [comment]
Hello @n4kre , can you please confirm everything is working fine at head?

**Comment by n4kre** [comment]
I do confirm :)
