### ISSUE TITLE
Tie default redirection to user in the same way as ACLs

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#200]
Hi,

Rather than a default redirection common to anyone, it could be tied to the user in the same way as ACLs are (any/groups/users).
The idea is to be able to achieve such a scenario, for instance: by default, anyone is redirected to some page, while users in the “admin” group are redirected to some other page, user “bob” is redirected elsewhere, etc.

In case you go for it, I would then suggest the following modifications:

- Remove notification pop-ups related to successful authentication (only maintain the ones related to failure). Instead, redirect either to `/secondfactor` after first factor authentication or to `/loggedin` in case the default redirection is made to a page not requiring 2FA; and to `/loggedin` in case of second factor authentication.
- Then, `/loggedin` could be dynamic:
  - Add “You can complete second factor authentication [here](https://login.example.com/secondfactor).” if user has not done so yet.
  - Remove “If you are not redirected in few seconds, click [here](https://private.example.com/lorem-ipsum).” in case there is no default redirection page for the user. Else, actually redirect the user to its default redirection page (this is the current behavior).
  - Remove “already” from “You are already logged in as **username**.”—weird to see it in case you have just logged in, and not necessary otherwise.
  - Keep “Click [here](https://login.example.com/logout) to log out.”, in any case.
- Make the redirection delay configurable in Authelia's config (in a global way).
- Always redirect users visiting back the login page to `/loggedin`: from there, the user will be able to both perform 2FA or log out (if you implement the behavior I have described so far). As of now, the user is redirected to the 2FA page in case he has not completed it yet: he cannot decide to log out—maybe he accesses only single auth protected domains and does even know what 2FA is about.

**Comment by clems4ever** [comment]
Hello @n4kre , I found out that I never replied to this proposal, my bad. Do you have a concrete use case or any example of something similar in an existing authentication system?

**Comment by clems4ever** [comment]
I will close this issue and reopen it if more users are interested in that feature.
