### ISSUE TITLE
Usernames enumeration (continued)

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#201]
Hi,

Getting back to #133: an invalid username submitted for password reset should result in the same behavior than an invalid username submitted for login, with regard to the response code sent back to the client.
As of now, the end-user asking to reset a password for a non-existent account receives an HTTP 401 – different from the code it receives in case a valid username has been submitted, thus allowing usernames enumeration.

I would suggest implement it in the same way as explained in #133.

**Comment by clems4ever** [comment]
Hello @n4kre , this issue is handled in #202 .

**Comment by clems4ever** [comment]
It reached the mainstream :).

**Comment by n4kre** [comment]
Hi,

Thank you @clems4ever!

In addition, I have noticed such an error is not logged anymore. Could you please log it again? This would be useful for anti-bruteforce software. :)
You could reuse the same message in case of an invalid username submission to the login form:`'[…] message='Reply with error 200: No user DN found for user '[…]''`
