### ISSUE TITLE
Custom mail_attribute never returns email addresses 

### ISSUE THREAD

**Issue by networkhell** [clems4ever/authelia#213]
I use a custom LDAP email attribute to retrieve my users email addresses. It seems that the function searchEmails does ignore the 'mail_attribute' from config.yml. So using a mail_attribute different from 'mail' is impossible!   

It just does not return any email address: 

`debug: LDAP: emails of user '******' are`

I think the problem is in the function searchEmails in dist/server/src/lib/ldap/Client.js

`            const emails = docs
                .filter((d) => { return typeof d.mail === "string"; })
                .map((d) => { return d.mail; });
`

There is no key named mail if you use a custom ldap attribute. I suggest a solution like this where the map and filter functions respect the settings file. 

`            const emails = docs
                .filter((d) => { return typeof d[that.options.mail_attribute] === "string"; })
                .map((d) => { return d[that.options.mail_attribute]; });
`

This works at least in my case. 

**The same problem exists when more than one email addresses are returned by LDAP.** But I did not dig deeper into that second issue.

**Comment by clems4ever** [comment]
Hello @networkhell ,

thank you for the report. I will add a test and try your fix. Regarding multiple emails per user, I think it is not supported (did not try though).

Clément.

**Comment by clems4ever** [comment]
Here is the PR that fixes the issue: #217 . Thank you for the hints.

**Comment by clems4ever** [comment]
The fix is in v3.7.1. Thanks.
