### ISSUE TITLE
LDAPs with self Signed Active Directory CA

### ISSUE THREAD

**Issue by demvil** [clems4ever/authelia#214]
HI,

I have an Active Directory and it has self signed certificates.

My configuration only works if I disable 
`Environment=NODE_TLS_REJECT_UNAUTHORIZED=0`
But I want to enable it.

I imported the certificates in Debian ca-certificates.
How can I use my self signed certificates with LDAPs.

**Comment by clems4ever** [comment]
Hello @demvil , what is the error you get when using the ldaps:// url to your LDAP?

**Comment by clems4ever** [comment]
Hello @demvil , can you please share the error you get?

**Comment by clems4ever** [comment]
@demvil , please re-open this thread if you still have the problem and can share the kind of error you're facing.
