### ISSUE TITLE
'Authentication session * was undefined. Resetting.'

### ISSUE THREAD

**Issue by ciroiriarte** [clems4ever/authelia#221]
Hi!, 

I'm trying Authelia on nginx + CentOS 7, I can see session keys are inserted in redis, but I cannot successfully login:

> abr 30 13:38:55 mfa-test.lan authelia[3853]: debug: SessionId='0bqRKhi4aehY2AZNNWoZWmiycxl0GSLd' ip='10.2.0.1' message='LDAP binding successful. Retrieved information about user are {"emails":["ciro.iriarte@xxxx"],"groups":["Portal"]}'
> abr 30 13:38:55 mfa-test.lan authelia[3853]: debug: date='Mon Apr 30 2018 13:38:55 GMT-0400 (-04)' method='POST', path='/api/firstfactor' requestId='fdcc1fe9-8bfe-4d33-bb2d-8d07a42b934d' sessionId='0bqRKhi4aehY2AZNNWoZWmiycxl0GSLd' ip='10.2.0.1' message='Authentication method for "" is "single_factor"'
> abr 30 13:38:55 mfa-test.lan authelia[3853]: debug: date='Mon Apr 30 2018 13:38:55 GMT-0400 (-04)' method='POST', path='/api/firstfactor' requestId='fdcc1fe9-8bfe-4d33-bb2d-8d07a42b934d' sessionId='0bqRKhi4aehY2AZNNWoZWmiycxl0GSLd' ip='10.2.0.1' message='Mark successful authentication to regulator.'
> abr 30 13:38:55 mfa-test.lan authelia[3853]: debug: date='Mon Apr 30 2018 13:38:55 GMT-0400 (-04)' method='POST', path='/api/firstfactor' requestId='fdcc1fe9-8bfe-4d33-bb2d-8d07a42b934d' sessionId='0bqRKhi4aehY2AZNNWoZWmiycxl0GSLd' ip='10.2.0.1' message='Redirect to 'undefined''
> abr 30 13:38:55 mfa-test.lan authelia[3853]: debug: date='Mon Apr 30 2018 13:38:55 GMT-0400 (-04)' method='GET', path='/loggedin' requestId='e1ce7b22-bd07-4772-a778-b0035b028830' sessionId='443ePuXSXjvo8GSaba7gkaZdqH0y7qK5' ip='10.2.0.1' message='Headers = {"host":"auth.test.com","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"https://auth.test.com/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,es-US;q=0.8,es;q=0.7,pt;q=0.6","x-forwarded-for":"10.2.0.1","x-forwarded-host":"auth.test.com","x-forwarded-server":"auth.test.com","connection":"Keep-Alive"}'
> abr 30 13:38:55 mfa-test.lan authelia[3853]: debug: date='Mon Apr 30 2018 13:38:55 GMT-0400 (-04)' method='GET', path='/loggedin' requestId='e1ce7b22-bd07-4772-a778-b0035b028830' sessionId='443ePuXSXjvo8GSaba7gkaZdqH0y7qK5' ip='10.2.0.1' message='Authentication session 443ePuXSXjvo8GSaba7gkaZdqH0y7qK5 was undefined. Resetting.'
> abr 30 13:38:55 mfa-test.lan authelia[3853]: error: date='Mon Apr 30 2018 13:38:55 GMT-0400 (-04)' method='GET', path='/loggedin' requestId='e1ce7b22-bd07-4772-a778-b0035b028830' sessionId='443ePuXSXjvo8GSaba7gkaZdqH0y7qK5' ip='10.2.0.1' message='Redirect to error 401: First factor has not been validated yet.'
> abr 30 13:38:55 mfa-test.lan authelia[3853]: debug: date='Mon Apr 30 2018 13:38:55 GMT-0400 (-04)' method='GET', path='/loggedin' requestId='e1ce7b22-bd07-4772-a778-b0035b028830' sessionId='443ePuXSXjvo8GSaba7gkaZdqH0y7qK5' ip='10.2.0.1' message='FirstFactorValidationError: First factor has not been validated yet.

It's like the application thinks that the user was not authenticated, although I received:

> Mark successful authentication to regulator.

**Comment by clems4ever** [comment]
Hello,
I think your issue is related to #216.

Can you please give more info about your setup? What version of authelia you're using? Do you use a docker image? Do you use the npm package? What is the LDAP server you're using?

**Comment by ciroiriarte** [comment]
Sorry for the missing information. I'm running Authelia through the NPM module.

CentOS 7.1: 3.10.0-693.21.1.el7.x86_64
nginx version: nginx-1.13.12-1.el7_4.ngx.x86_64
npm version: npm-3.10.10-1.6.14.0.1.el7.x86_64
node version: nodejs-6.14.0-1.el7.x86_64
Redis server version=redis-3.2.10-2.el7.x86_64
Mongodb version = mongodb-server-2.6.12-6.el7.x86_64
Authelia:  authelia@3.7.1

The backend is a Windows 2008 AD server, the connection is working the logs reflect atributes retrieved that are related to the user trying to authenticate (group + email)

**Comment by ciroiriarte** [comment]
NginX configuration:

server {
    listen 80;
    server_name auth.iriarte.it;

    location = /api/verify {
        include conf.d/default_headers;
        # Set original requested Host from X-Forwared-Host.
        # Of course, the external Nginx server protecting his resources
        # must have properly set this header, as configured in this how-to.
        proxy_set_header Host $http_x_forwarded_host;
        proxy_pass http://127.0.0.1:8080;
    }

    # Authelia's frontend

    location /secondfactor/totp/identity/finish {
        # We don't want the user web browser to cache
        # TOTP secrets / QR codes, for security purposes.
        add_header Cache-Control "no-store";
        add_header Pragma "no-cache";
        include conf.d/default_headers;
        include conf.d/proxy_params;
        # Pass to Authelia's backend
        proxy_pass http://127.0.0.1:8080;
        proxy_intercept_errors on;
        if ($request_method !~ ^(POST)$){
            error_page 401 = /error/401;
            error_page 403 = /error/403;
            error_page 404 = /error/404;
        }
    }

    location / {
        include conf.d/default_headers;
        include conf.d/proxy_params;
        # Pass to Authelia's backend
        proxy_pass http://127.0.0.1:8080;
        proxy_intercept_errors on;
        if ($request_method !~ ^(POST)$){
            error_page 401 = /error/401;
            error_page 403 = /error/403;
            error_page 404 = /error/404;
        }
    }
}

**Comment by clems4ever** [comment]
Hello @ciroiriarte , you are at least missing the parameter forwarding authentication requests to Authelia which would be something like this in your case: `auth_request /api/verify;` to be added in `/` section. How did you build your nginx configuration? Were you inspired by something?

You'll find a complete example of nginx configuration in `examples/compose/nginx/portal/nginx.conf`. Do not hesitate to ask if there is something you don't understand, I will make it clearer by adding comment to the configuration file directly. Or you can also do it if you want to contribute :).

**Comment by ciroiriarte** [comment]
Hello!, 

I've used this configuration as reference:

https://github.com/clems4ever/authelia/issues/178

I still didn't configure any site to be "protect" by Authelia, I was expencting to "login to" Authelia to enroll a U2F key. Probably I missunderstand hoy it works.

**Comment by clems4ever** [comment]
Ok, I did not test this tutorial myself so I cannot guarantee anything about it. I advise you to try understanding the minimal configuration I gave you for Authelia to work and then augment this configuration with what is in this tutorial if you need it.

Regarding the question you have on how it works, here is a little explanation: Authelia is an HTTP server validating authentication requests forwarded from the nginx reverse proxy to `/api/verify`. If a user visiting  one of your protected app is not authenticated, nginx is supposed to redirect to Authelia's portal for the user to login and register a second factor or validating the second factor if already registered. After that, your user will be able to log in once for all apps protected by Authelia (single sign-on). Clearer?

**Comment by clems4ever** [comment]
I also advise you to test the docker-compose environment described in the README. With only a few commands, this is definitely the fastest way to test the app and see how it works.

**Comment by clems4ever** [comment]
Hello @ciroiriarte , have you solved your issue? if not yet, please re-open the ticket.
