### ISSUE TITLE
Use Authelia without openLDAP

### ISSUE THREAD

**Issue by clicksports** [clems4ever/authelia#223]
Hello, is it possible to use Authelia without openLDAP?

**Comment by clems4ever** [comment]
Hello @clicksports , apparently some users tried with MS Active Directory and seemed to work.
Thanks.

**Comment by clicksports** [comment]
Hello, @clems4ever is it possible to use it without any LDAP-System?

**Comment by clems4ever** [comment]
@clicksports , where would you retrieve the user/password from in that case?
Authelia does not support static databases of users.

**Comment by clicksports** [comment]
@clems4ever, Is it possible to save the user data into the database?
