### ISSUE TITLE
[question] Browser https proxy support?

### ISSUE THREAD

**Issue by jakegroves** [clems4ever/authelia#226]
Hey :)

I have been testing out the authelia stack you provide on docker on Debian Jessie.
I have managed to get it working with setting the 'server_name' directive to '_' so it accepts any server name and does the 2fa auth.

However, whenever I set up my browser to proxy https requests through to the authelia host on port 8080, the nginx logs just respond with code 400.

my authelia portal nginx:
```
worker_processes  1;
events {
    worker_connections  1024;
}
http {
     server {
        listen 80 default;
        rewrite (.*) https://$host$1;
     }
     server {
         listen 443 ssl default_server;
         server_name _;
         resolver 127.0.0.11 ipv6=off;
         set $upstream_endpoint http://nginx-authelia;
         ssl on;
         ssl_certificate     /etc/ssl/server.crt;
         ssl_certificate_key /etc/ssl/server.key;
         add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
         add_header X-Frame-Options "SAMEORIGIN";
         location / {
             proxy_set_header  Host $http_host;
             proxy_set_header  X-Original-URI $request_uri;
             proxy_set_header  X-Real-IP $remote_addr;
             proxy_set_header  X-Forwarded-Proto $scheme;
             proxy_intercept_errors on;
             auth_request_set $redirect $upstream_http_redirect;
             proxy_pass        $upstream_endpoint;
             if ($request_method !~ ^(POST)$){
               error_page 401 = /error/401?rd=$redirect;
               error_page 403 = /error/403;
               error_page 404 = /error/404;
             }
         }
     }
}
```

And I end up getting 400 code:
`x.x.x.x - - [14/May/2018:17:25:41 +0000] "CONNECT hostname:443 HTTP/1.1" 400 174 "-" "-"`

So I am wondering before I sink more time into the authelia solution, is what I am trying to achieve even supported/possible with your 2fa solution? As all I want is to proxy all my browser requests through authelia.

workflow:
E.g. proxy = authelia.foo.com.
me -> db.foo.com -> auth against authelia.foo.com -> success -> redirect back to db.foo.com (authed session lives for x time)

**Comment by jakegroves** [comment]
Thanks for your prompt response @clems4ever. 
I don't understand how it would not support HTTPS requests? As the examples you provide are running over HTTPS ?
Is this not solvable via nginx?
Also is it a feature on the roadmap? 

Thanks for your time in replying!

**Comment by clems4ever** [comment]
Sorry, I read your question a bit too fast, I thought you were forwarding authentication requests to Authelia in HTTPS. But after reading again your configuration, I was wrong.

Can you please try this for redirection of HTTP to HTTPS:

```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
}
```

**Comment by jakegroves** [comment]
It turns out to be an issue with nginx as it does not handle 'CONNECT' requests. (which is the nginx proxy server handling the proxying of the established tcp connection, and not the actual get/post/put/delete requests you would normally do on a reverse proxy.)
I have ended up recompiling nginx and making a docker image to support the module: [ngx_http_proxy_connect_module](https://github.com/chobits/ngx_http_proxy_connect_module)
and added some basic directives from that module.

Basic nginx proxying worked, I just need to test it with the authelia stack tomorrow.

Will update on how the stack handles it.
Thanks for your time

**Comment by clems4ever** [comment]
Glad you found the solution :).
