### ISSUE TITLE
Authelia does not reconnect correctly to ldap server after inactivity period

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#23]

**Comment by jkaberg** [comment]
Just letting you know I've also experienced this. It sucks somewhat as Authelia currently doesn't keep track of authenticated users, and an 'quick' fix for this particular issue is to restart the Authelia container

**Comment by clems4ever** [comment]
Actually, after you face the issue if you log in a second time it should work, even without restarting the container.

**Comment by clems4ever** [comment]
I'm currently trying to reproduce with more verbose logs to fix the issue.

**Comment by clems4ever** [comment]
Hello,
I haven't find the root cause yet but I'm trying to change a bit the way Authelia connects to the server. Indeed, I think the bug is due to long connection being closed after a timeout or something. Thus, after my fix I'm opening a connection for each operation performed against the LDAP server. That way, the ldap client avoid keeping connection until it becomes idle. 
I'm testing this new code on an env where I can reproduce.

**Comment by clems4ever** [comment]
The fix is working. It will be merged soon!

**Comment by clems4ever** [comment]
Hello @jkaberg ,
I fixed it at v3.1.4. It's being published in npm and Dockerhub.
