### ISSUE TITLE
LDAP Query with Cyrillic

### ISSUE THREAD

**Issue by andrvas** [clems4ever/authelia#230]
HI!
I tried to set up Authelia with Active Directory.
I  get success only if LDAP Query doesn't contain a cyrillic.

Nonworking Config example:
`base_dn: DC=MCPLAT,DC=RU`
`additional_users_dn: OU=ДИТ (Департамент информационных технологий),OU=_Users,OU=Бизнес-Центр Wall Street,OU=2-ая Советская 27,OU=_ООО НКО Мобильная Карта_`

What i see in tcpdump:
`ou=.......(........................................................................),.ou=_Users,.ou=............-...........Wall.Street,.ou=2-.....................27,.ou=_..........................................._,.dc=MCPLAT,.dc=RU`

Can you somehow fix this?

**Comment by andrvas** [comment]
Hello! I make huge mistake.
Tcpdump cannot display cyrillic symbols in terminal output (That's why i saw the dots in query).
I make dump into file and checked it with wireshark. The outgoing query to ldap server was correct.
The error was in config.yml file where the variable "users_filter" equals "cn={0}" in default.
I guess that more correct default option is "users_filter: sAMAccountName={0}".
Thanks a lot and sorry for the trouble!

**Comment by clems4ever** [comment]
Hello @andrvas , I'm interested in knowing if the change works and if Authelia supports Cyrillic. Please keep me posted if you do the test.

**Comment by andrvas** [comment]
Yep. Authelia works with cyrillic but only with user binding one by one. 
I tried to bind by group membership and i didn't have enough time for testing but i always got the error that my user member hadn't access to protected domain.
Mabe it's needed more specific option in config.yml for groups.
