### ISSUE TITLE
 failed to connect to server [mongo:27017]

### ISSUE THREAD

**Issue by jad-47** [clems4ever/authelia#231]
Hello, 
When I write the following command for installation and configuration 

docker run -v /Users/amjadhamad/Desktop/authelia-master/config.template.yml:/etc/authelia/config.yml -v /Users/amjadhamad/Desktop/authelia-master/dir:/var/lib/authelia clems4ever/authelia 

The result is :  

Unhandled rejection MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]
    at Pool.<anonymous> (/usr/src/node_modules/mongodb-core/lib/topologies/server.js:505:11)

How can I solve this issue? 

Thanks,

**Comment by clems4ever** [comment]
Hello @jad-47,

please follow the steps from the README. You should be able to deploy a complete working environment using docker-compose.

Thanks,
