### ISSUE TITLE
404 error for api/verify

### ISSUE THREAD

**Issue by ejparker12** [clems4ever/authelia#234]
Now that I've got the authentication process of authelia working again I have discovered that the verification in nginx isn't working anymore either (it seems /api/verify isn't working):

Nginx Error:
`2018/06/15 15:32:49 [error] 7541#7541: *3 auth request unexpected status: 404 while sending to client, client: 172.16.41.30, server: portal.actcur.com, request: "GET /authenticated.php HTTP/1.1", host: "portal.actcur.com`

Partial nginx config:
```
  location /auth_verify {
    internal;
    proxy_pass_request_body off;
    proxy_set_header  X-Original-URI $request_uri;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  Host $http_host;
    proxy_set_header  Content-Length "";

    proxy_pass        http://authelia.example.com:8080/api/verify;
  }
  location /authenticated.php {
    auth_request /auth_verify;

    error_page 401 =302 https://portal.example.com/unauthenticated.php;

    try_files $uri $document_root$fastcgi_script_name =404;
    fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi.conf;
    index index.php;

    root /srv/http/portal/public;
  }
```

I don't get any error message in authelia, and I can access the login page via using "curl authelia.example.com" from my portal without issues - but for whatever reason the /api/verify url appears to be throwing back a 404 error. This is whether I point auth_verify to the nginx proxy on my authelia server or point it directly to authelia itself (the current configuration)

Running "curl http://127.0.0.1:8080/api/verify" from the authelia server returns:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/verify</pre>
</body>
</html>
```

Node version 8.11, NPM version 6.0.1, Authelia 3.7.1

**Comment by ejparker12** [comment]
Fixed it - npm was reporting the wrong version of Authelia being installed - it was claiming 3.7.1 was installed, but the actual version was one from way back before you changed the verify url from /verify to /api/verify. Uninstalling the authelia package and reinstalling it fixed the issue.

**Comment by clems4ever** [comment]
Hello @ejparker12 , I'm glad you found a solution. Thanks.
