### ISSUE TITLE
Session cookie: customizable name and do not forward to Nginx backend

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#235]
Hi,

The session cookie name (field `name` in `ExpressSession.SessionOptions`) should be customizable: `connect.sid` is the default name for Express-Session, and this can pose a lot of troubles if the backend that is protected by Authelia also uses this name for some of its cookies, for obvious reasons.

Then, it would be nice not to forward Authelia's session cookie to the backend, for security reasons: .
There's not much Authelia can do about it, by design – the session cookie is indeed set at the base domain –; but Nginx can hopefully help: https://librenepal.com/article/remove-specific-cookies-with-nginx/

**Comment by n4kre** [comment]
FYI, I've updated my [deployment guide](#178) assuming you'll take this security remark into account (cf. file `authelia_sso_params`) ;)

Feel free to update the Wiki article in accordance.

**Comment by clems4ever** [comment]
Very good remark! I will definitely add the option in the configuration file and update the documentation with your updates.
I will also put the documentation directly in the source tree so that you can create a pull request for next time.

**Comment by naggie** [comment]
I suggest that the cookie name should have a default, and that default should be namespaced to authelia. For example: `authelia_session`. This will make generalising an nginx configuration that accounts for the warnings given by @n4kre in  `authelia_sso_params`.

**Comment by clems4ever** [comment]
Merged.
