### ISSUE TITLE
Dockerfile doesn't build

### ISSUE THREAD

**Issue by hadmut** [clems4ever/authelia#238]
Hi,

./scripts/example-commit/deploy-example.sh

fails to build with 

Step 5/11 : COPY dist/server /usr/src/server
ERROR: Service 'authelia' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder900301777/dist/server: no such file or directory
Building authelia

probably because the Dockerfile contains

COPY dist/server /usr/src/server
COPY dist/shared /usr/src/shared

while the directories server and shared  and in the top level directory and not under dist/.

regards

**Comment by clems4ever** [comment]
Hello @hadmut , thank you for the report. I will check what's happening and fix it, hopefully today.

**Comment by clems4ever** [comment]
Sorry, for the delay. You're issue is coming from the fact that authelia needs to be compiled before the docker image can be built. Please follow the steps mentioned in the README.
Please re-open the ticket if you still have issues while building the image.

Thanks.
