### ISSUE TITLE
Invalid email credentials result in confusing 401 Unauthorised page when registering 2FA token

### ISSUE THREAD

**Issue by naggie** [clems4ever/authelia#239]
Unknowingly, I had incorrect SMTP credentials such that the confirmation/registration emails could not be sent. As a result, when clicking on the link to register a hardware token or google authenticator token I get the following error:

![image](https://user-images.githubusercontent.com/208440/42374733-012ebbf2-8111-11e8-8d56-9dc6c165a9ac.png)

This was very confusing until I looked at the debug log output of the system. Perhaps the message to the user should be something correct like "Internal error" or such.

Thanks
Callan

**Comment by clems4ever** [comment]
Hello @naggie , this behavior is expected for security reasons. It protects against username enumerations. You can refer to #133 to get more info.
