### ISSUE TITLE
Move to Docker alpine image

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#25]
The current official image is at 713MB, quite big imo. 

Perhaps we can get this a bit smaller? 😄

**Comment by clems4ever** [comment]
Hello @jkaberg , you are right. Alpine is a good way to improve the image size but I think there is something simpler I can do by not installing dev packages in the image. I will replace **npm install** by **npm install --production** and see how it goes.

**Comment by clems4ever** [comment]
Clearly better now ! :).

![image](https://cloud.githubusercontent.com/assets/3193257/26035141/b75d8bbc-38c7-11e7-8bec-4c46817562a5.png)

**Comment by jkaberg** [comment]
Very nice! Thanks 😄
