### ISSUE TITLE
Add ability to configure 2FA name in google authenticator

### ISSUE THREAD

**Issue by whiskerch** [clems4ever/authelia#250]
Is it possible to configure the Name of the 2FA token that gets imported to Google Authenticator? 

At the moment, when a user sets up 2FA - the entry in google authenticator shows 'authelia.com' as the name

**Comment by clems4ever** [comment]
Hello, yes it is possible and I've just seen this is not documented and not even present in the config template. I will add it.

You can set your own issuer by adding

```
totp:
  issuer: yourissuer.com
```

**Comment by clems4ever** [comment]
@whiskerch , you can contribute by adding it to the config template if you wish.

**Comment by whiskerch** [comment]
Cheers! 
I'll make the change and raise a PR now :)

**Comment by clems4ever** [comment]
Merged!
