### ISSUE TITLE
Base path should be optional

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#26]
Currently Authelia seems hardcoded to use /authentication for all calls. 

Perhaps this could be made optional? 😄

**Comment by clems4ever** [comment]
Hello @jkaberg , I will give it a try.

**Comment by jkaberg** [comment]
I see you've got an seperate branch for this. Somehow the new alpine docker container listens on / instead of /authentication. Haven't checked as to why yet but thought I'd let you know.

**Comment by clems4ever** [comment]
The feature has been merged. "/authentication/" base path has been removed with #31 .
