### ISSUE TITLE
Responsive UI

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#27]
In it's current state, Authelia is not responsive. 

Perhaps we could get a more responsive UI which adapts to small and big screens? 😄

**Comment by clems4ever** [comment]
Hello @jkaberg , thank you for your feedback. Indeed this is something I'd like to work on. I'm currently migrating the framework to typescript but once done I'll rewrite the frontend so that it becomes more responsive.

**Comment by clems4ever** [comment]
Hello @jkaberg , the work is ongoing, I rewrote the client in typescript and I'm currently simplifying the endpoints. I'm also reworking the frontend to make it beautiful and responsive and make it better support history (being able to go to previous page during second factor). The work is in a dev branch but is not yet finished.

**Comment by clems4ever** [comment]
Hello @jkaberg,
What do you think about this frontend ? 
![image](https://user-images.githubusercontent.com/3193257/26898519-9726279c-4bcc-11e7-96e7-0a4e29a06d6a.png)
Fully responsive, obviously.

**Comment by jkaberg** [comment]
@clems4ever Looking nice, well done! :smile:

**Comment by clems4ever** [comment]
Not done yet but in progress :).
