### ISSUE TITLE
Implement "Keep me logged in" on a given device.

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#270]
Sometimes users would like to stay logged in on a certain device to avoid authenticating every now and then.

**Comment by clems4ever** [comment]
#287 , implements it.

**Comment by n4kre** [comment]
Hi @clems4ever,

Thank you for this new feature! :)

From a security stand point, I guess it would however make sense to let the administrator decide whether it should be allowed or not.
In a nutshell, an `allow_keep_me_logged_in` boolean parameter in Authelia configuration file to toggle this feature on or off would be nice.

**Comment by clems4ever** [comment]
Followed in #291 .
