### ISSUE TITLE
Minimal Installation - 2FA secrets location

### ISSUE THREAD

**Issue by p-rintz** [clems4ever/authelia#278]
Hello,

I have the minimal installation working, but currently every time I remake the container, the 2FA data will be reset, as if I never had configured it.  So I obviously need to give Authelia some persistent volume for this, but I do not know where this information is saved.

Where does Authelia, in the minimal installation, save this 2FA information?

This is not about the users/password, just about the 2FA information.

Thanks.

**Comment by clems4ever** [comment]
You can see this in https://github.com/clems4ever/authelia/blob/master/server/src/lib/configuration/schema/StorageConfiguration.ts

**Comment by p-rintz** [comment]
Thanks. I created a PR to improve the minimal config example. (and also add a docker swarm example)

Now I only need to take some time to make traefik internal authentication work with authelia and Im a happy camper.

**Comment by clems4ever** [comment]
@p-rintz , this is awesome! Thank you very much. I'll take a look at the PR.

**Comment by clems4ever** [comment]
You'll please some other users with Traefik by the way :).
