### ISSUE TITLE
LdapError: Invalid Credentials

### ISSUE THREAD

**Issue by joe307bad** [clems4ever/authelia#279]
I am running authelia in docker and am having some trouble logging in. Below is a more detailed error logs, but every time I try to use user: `authelia_admin` & password: `password`, I get an error `LdapError: Invalid Credentials`. Below the error message is a link to my config.yml. What am I missing here?

![image](https://user-images.githubusercontent.com/1916208/46230176-c45e5680-c335-11e8-8220-7de832f3f069.png)

[https://gist.github.com/joe307bad/5fb468766efbc28dcd5917a308e0a6e4](https://gist.github.com/joe307bad/5fb468766efbc28dcd5917a308e0a6e4)

**Comment by joe307bad** [comment]
Hey @clems4ever, thanks for responding.

Here are the tags I am using for all my docker images:
- clems4ever/authelia - latest
- schickling/mailcatcher - latest
- clems4ever/openldap - latest
- osixia/phpldapadmin - 0.6.11

> How did you configure the admin user and its password in the LDAP? 

I am not sure I did anything for this. I figured if it was configured correctly in the config.yml, the user would automatically get created. Is there any documentation for adding LDAP users?

>  Can you check you can bind using ldapsearch?

Whenever I `exec` into either of the LDAP containers, the `ldapsearch` command is not available. Where should I be able to use this command? On the host?

**Comment by clems4ever** [comment]
if you're using the image I provide for openldap then the user `authelia_admin` does not exist. You should put back the user used in config.template.yml in your configuration unless you change the admin user manually.

**Comment by joe307bad** [comment]
Even while using the following LDAP admin user configuration taken from the `config.template.yml` file:
<pre lang="yaml">
user: cn=admin,dc=example,dc=com
password: password
</pre>
And then trying to login via the authelia frontend using username: `admin` and password: `password`, I am still getting the error shown in the screenshot provided above (`LdapError: Invalid Credentials`)

>...unless you change the admin user manually.

How do you change the admin user manually?
Where should I be able to access `ldapsearch` from?

**Comment by joe307bad** [comment]
Thanks @clems4ever. 

I actually prefer spinning up my containers via ansible scripts and have been porting your compose files over to that. [Here is what I have for the LDAP portion of this infrastructure](https://gist.github.com/joe307bad/a7cb7ae1b1e9ca2001ad78efd6b39882)

Also, I `exec`ed into your `clems4ever\openldap` container, and noticed there were no LDAP folders under `/usr/bin`. Then I installed `ldap-utils` via ` apt-get install ldap-utils` inside the container and then was able to use `ldapsearch`. Then, when trying to search for all users via ` ldapsearch -h localhost -p 1389 -b "dc=example,dc=com"`, I got an error `ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)`.

So I think I am having trouble getting the LDAP server to install correctly.

**Comment by joe307bad** [comment]
Running the command `ldapsearch -x -b "cn=admin,dc=example,dc=com"`

<pre lang="bash">
# extended LDIF
#
# LDAPv3
# base <cn=admin,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# search result
search: 2
result: 32 No such object

# numResponses: 1
</bash>

**Comment by joe307bad** [comment]
I was able to move forward with my admin user by using the [osixia/docker-openldap](https://github.com/osixia/docker-openldap) image and the following LDAP configuration within my authelia `config.yml`
<pre lang="yaml">
# The authentication backend to use for verifying user passwords
# and retrieve information such as email address and groups
# users belong to.
#
# There are two supported backends: `ldap` and `file`.
authentication_backend:
  # LDAP backend configuration.
  #
  # This backend allows Authelia to be scaled to more
  # than one instance and therefore is recommended for
  # production.
  ldap:
    # The url of the ldap server
    url: ldap://openldap

    # The base dn for every entries
    base_dn: dc=example,dc=org

    # An additional dn to define the scope to all users
    # additional_users_dn: ou=users

    # The users filter used to find the user DN
    # {0} is a matcher replaced by username.
    # 'cn={0}' by default.
    users_filter: cn={0}

    # An additional dn to define the scope of groups
    #additional_groups_dn: ou=groups

    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # 'member={dn}' by default.
    groups_filter: (&(member={dn})(objectclass=groupOfNames))

    # The attribute holding the name of the group
    group_name_attribute: cn

    # The attribute holding the mail address of the user
    mail_attribute: mail

    # The username and password of the admin user.
    user: cn=admin,dc=example,dc=org
    password: admin
</pre>

Notice, I commented out `additional_groups_dn: ou=groups` and `additional_users_dn: ou=users`. I don't know if this will reintroduce more issues (since I don't know the significance of the custom `clems4ever/openldap` image), but I think this at least confirms that there is something amiss with my authelia container communicating with my `clems4ever/openldap` container. Specifcally, I think there is an issue with my authelia container not being able to find my admin user inside my `clems4ever/openldap` container.

**Comment by nightah** [comment]
Even with the [osixia/docker-openldap](https://github.com/osixia/docker-openldap) image you will still need to create your relevant users and/or groups.
Whether you nest them inside a specific OU like the defaults in the `config.yml` will be completely up to you.

I suggest looking at a tool to manage your LDAP instance when installed and running [osixia/phpldapadmin](https://github.com/osixia/docker-phpLDAPadmin) or [Apache Directory Studio](https://directory.apache.org/studio/downloads.html) both will do the trick.

**Comment by joe307bad** [comment]
Thanks @nightah. 

But can you explain why my query `ldapsearch -x -b "cn=admin,dc=example,dc=com"` returned zero results when using `clems4ever/openldap` container?

And also, I had to manually install `ldapsearch` within that container. Shouldn't this by present within this container to begin with?

**Comment by nightah** [comment]
@joe307bad I haven't used that container so I wouldn't be able to tell you what the root structure should look like. It very well could actually be empty because there are two ways to create a root/admin user that or may not show up in the above query.

From what I can tell just quickly playing with the container you're correct that `ldapsearch` isn't bundled in.

Realistically if you use phpldapadmin and/or Apache Directory Studio you won't need ldapsearch.

**Comment by clems4ever** [comment]
@nightah is right, you can try with the phpldapadmin

**Comment by joe307bad** [comment]
Thanks guys, I ended up using the `windfisch/phpldapadmin` docker image and was able to login with `      cn=admin,dc=example,dc=org` with the default admin password. From there, I was able to add users and go through the authelia login flow. I am going to move on to researching how to seed users.
