### ISSUE TITLE
Share matrix CSS theme with community

### ISSUE THREAD

**Issue by BankaiNoJutsu** [clems4ever/authelia#285]
Hello,

This is not really an issue, however i wanted to share this if anyone interested.
Feel free to close it, if it is posted at the wrong place.

It is a matrix style skin for authelia.

[authelia_matrix_dist_final.zip](https://github.com/clems4ever/authelia/files/2498950/authelia_matrix_dist_final.zip)

It looks like this:
![authelia_matrix](https://user-images.githubusercontent.com/2241519/47264722-74317900-d51c-11e8-9f9e-e0237a4d09d4.png)

I modified the css, and for the totp register i had to add a small white border for it to be recognised by the qr scanners. Also added a js file for the matrix style, which is a bit CPU heavy, beware :)

Hope you like it, and I can share sources if you like.

**Comment by jmccoy555** [comment]
That should scare away any unwanted visitors 😃 

I'm going to have to give it a go when I get 10mins.

**Comment by clems4ever** [comment]
Hello @BankaiNoJutsu , this theme looks great! We should definitely find a way to share it with the community. I think we should add a "themes" directory with subdirectories for each new theme.

There is now way to easily switch theme dynamically in Authelia yet but we might find a way in a near future. In the meantime let's create a directory called "themes", a "matrix" subdirectory holding the css and let's create a tuto explaining how to update the theme in a README under "themes".

Sound good? Can you do the PR?

**Comment by clems4ever** [comment]
Hello @BankaiNoJutsu , would you like to contribute with your theme?

**Comment by BankaiNoJutsu** [comment]
Hey @clems4ever, good idea to already create the folder structure. I am finishing some minor things on the theme, and will create a pull request once all is ready.

Also doing the readme for quick change of themes. Sorry it may take a while, quite busy those days.

**Comment by BankaiNoJutsu** [comment]
Closing, as pull #309 is merged.
