### ISSUE TITLE
Convert the project into typescript

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#29]

**Comment by SerialVelocity** [comment]
Slightly unrelated note, but have you tried Elm? It's basically what I use for everything I build front-end related now :)

http://elm-lang.org/

**Comment by clems4ever** [comment]
Hello @SerialVelocity , I did not know Elm but I'll definitely have a look. Since the project has already been rewritten in typescript, is there any reason to use it anymore?

**Comment by SerialVelocity** [comment]
@clems4ever Nope, no reason at all (only if you want to learn a new language :P )

**Comment by clems4ever** [comment]
Good, thank you for the info. :)
