### ISSUE TITLE
Fix open redirection vulnerability.

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#290]
Hi @clems4ever,

Authelia is vulnerable to [open redirection](https://portswigger.net/kb/issues/00500100_open-redirection-reflected), which can aid an attacker in conducting a phishing attack.

To prevent this issue, I would suggest to add a parameter in Authelia configuration file `allowed_rd` which value would be a regex matching URLs determined as safe by the administrator. Then, the `rd` URL parameter would always be checked against this `allowed_rd` regex before actually allowing or not the redirection upon successful login.

**Comment by clems4ever** [comment]
Nice catch!

**Comment by clems4ever** [comment]
@n4kre , instead of introducing a new parameter we could simply verify the redirection URL is within the domain. What do you think?

**Comment by n4kre** [comment]
Simple, yet effective: sounds good!
