### ISSUE TITLE
Deploying Authelia locally issue

### ISSUE THREAD

**Issue by darkquasar** [clems4ever/authelia#295]
Hi there, what an amazing project you started! Congrats.

I've been trying to setup Authelia locally using docker-compose without success. I have many doubts but before I go on pasting the different configs, I would like to understand whether this is possible at all? As I understand, this bit in Authelia's config.yml says: 

```
 # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer. 
  domain: something.com
```

However, what do I set this value to if I'm testing it locally and I don't have a domain? My apps are all in different containers and there's no "domain" gluing it all together. 

Regards,
Diego

**Comment by darkquasar** [comment]
closing issue since I require more tests before engaging the developer of Authelia! :)

**Comment by clems4ever** [comment]
Hello @darkquasar , in the documentation I described how you should set up your /etc/hosts to be able to query the sub-domains of example.com to use the test environment. You should do the same for something.com.

**Comment by darkquasar** [comment]
Thanks mate! I actually read all your docs, but I wasn't able to make it work until I realized that, due to me running Authelia in a nested virtual environment (docker inside vm inside another vm), I had to adjust all "layers" of DNS resolution. It's working its magic now! can't thank you enough for this project!

**Comment by clems4ever** [comment]
I'm really happy to hear that it works now and to know that it suits your needs. There are a lot more to come so if you're a developer and you want to contribute, do not hesitate to give a hand!

**Comment by darkquasar** [comment]
Hi man, I know nothing about node.js programming and with JS all I can do really is to RE obfuscated malware haha. So I can't really give you a hand in there, however, I did create a nice composition out of Authelia + Sphinx + AWS to come up with private documentation sites for FREE. I created a whole tutorial for it here: https://www.eideon.com/2018-11-10-THL04-AwesomeKB/ There is also a working demo of this without 2FA in https://demo.awesomekbs.com

My followers base is pretty lame, but hopefully, it will bring up some further attention to Authelia and perhaps some savvy dev guys that can lend you a hand ;)

Thanks again for your great contribution!

**Comment by clems4ever** [comment]
Hello @darkquasar ,

that is really awesome! Indeed that could shed some light on Authelia and make developers aware that it exists. That's really cool, thank you for that!

In the meantime, I also have many improvements in the pipeline and among those the support for OAuth as you mention when talking about Cloudflare. Stay tuned, I'm also revamping the UI to make it look more professional and allow a lot more features like displaying the authentication logs, add multiple 2F devices per user or add a management portal.

I really want to thank you for this article!
