### ISSUE TITLE
got error 502 with dockerhub deployment

### ISSUE THREAD

**Issue by z-afshar** [clems4ever/authelia#296]
Hello,

I deploy authelia from dockerhub and get error 502 (bad gateway) when visiting https://my-server-ip:8080
mailcatcher is working on http://my-server-ip:8085

**Comment by clems4ever** [comment]
Hello @z-afshar , please have look at the documentation. You would see that you need to setup some stuff and you should not access the resource via IP directly.
If something is still unclear after reading please open a new issue so that I can improve the doc.
