### ISSUE TITLE
Use SMS notification as a 2nd factor

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#30]

**Comment by mnlbox** [comment]
@clems4ever any news about this?
If we can call a REST endpoint we can send TOTP as SMS. Yes?

**Comment by clems4ever** [comment]
Hello @mnlbox , no advancement on this topic yet. Code sent by SMS is indeed what I had in mind, no TOTP since few seconds to validate the code is a bit too short in that case.

**Comment by mnlbox** [comment]
@clems4ever Thanks for your reply and this awesome project.

**My suggestion:**
I think we need some help and tutorial about use of this with popular tools (for example parse platform, firebase, ...)
___
**My question:**
Are you any plan for this issue? (SMS based two factor)
___
**Maybe useful:**
I implement this later with https://github.com/speakeasyjs/speakeasy based on this article in Loopback:
https://jordankasper.com/two-factor-authentication-with-loopback/

**Comment by clems4ever** [comment]
Glad you like it! There are plenty of things to improve Authelia. I don't know all of those projects but you can definitely contribute by writing some documentation for them if you use them, it might be helpful to other users.

After second thought we might use TOTP to generate those tokens but we'll need to extend the expiration time to say 5-10 minutes or so. Speakeasy is already used in Authelia for TOTP tokens.

I did not know loopback but it seems it has a different purpose: authenticate users at the level of the application. It means you need to patch your entire fleet to support 2nd factor everywhere. At the contrary, the advantage of having Authelia set up is that 2nd factor authentication is just a matter of config and your whole fleet is protected right away. Plus, the authentication portal is unified.

**Comment by clems4ever** [comment]
@mnlbox , I wake up an old topic but I'm wondering: do you use any platform sending SMS and providing an API?

**Comment by mnlbox** [comment]
@clems4ever I completely migrate to http://keycloak.org
But I see authelia again now. It seems many improvement done later in this repo.
Can you compare authelia vs keycloak? Maybe I can come back again here :wink:

**Comment by nightah** [comment]
@clems4ever I would probably recommend Twilio for SMS if you’re considering adding that as a feature. Otherwise Duo SMS might also be another natural option considering you’re using the Push feature already.

**Comment by naggie** [comment]
@clems4ever 

https://www.pindrop.com/blog/nist-plans-to-drop-sms-for-two-factor-authentication/ suggests that NIST are going to drop SMS for 2FA. Considering it is becoming an increasingly used attack vector, you may want to consider not implementing this at all.

**Comment by clems4ever** [comment]
Gotcha, I also heard about it. I'm closing the issue.

**Comment by mnlbox** [comment]
@naggie But now many application use SMS for 2FA. For example Instagram, WhatsApp, ...

**Comment by naggie** [comment]
Yes they do. It's a problem.

**Comment by mnlbox** [comment]
@naggie No I think it's not a problem. 2FA over SMS still using and it doesn't deprecate at all so I think a good and complete authentication solution should support this feature too.

**Comment by clems4ever** [comment]
Hello @mnlbox , for the time being Authelia is used by many people who don't complain about the lack of this feature. I'd be interested to have more feedbacks on the topic. My opinion has always been mixed because, like @naggie, I also read a lot of articles telling about the security issues.

So it's basically not a no-go but in my opinion the next big authentication mechanism with mobile phone is push notifications. More and more applications use it lately. It's gonna be my next priority over SMS.
I'd be ok if someone introduces SMS and make it optional though because I can understand that in some cases the user has no access to internet on his phone and could prefer using SMS over TOTP for instance.
