### ISSUE TITLE
UI problem in the second factor authentication (v.3.10.0)

### ISSUE THREAD

**Issue by szimszon** [clems4ever/authelia#304]
Hi,

I wonder if you could help me.

I have an issue with the 3.10.0 version of authelia in the /secondfactor page.
I have no u2f extension installed in Firefox. But there is an iframe in the page which source is not accessible (because of the missing extension).
![kep](https://user-images.githubusercontent.com/745542/49075764-c1012180-f237-11e8-9c07-45bf6904668b.png)
And this is ugly:
![kep](https://user-images.githubusercontent.com/745542/49075799-d8d8a580-f237-11e8-900c-9cc918c8c3d6.png)

Could you please make it hidden in case of the absence of the extension? Thank you!

**Comment by clems4ever** [comment]
Hello @szimszon , thank you for reporting. I will try to find a way to detect if the browser has U2F enabled and load the lib only if necessary. That should solve this issue.

I'll let you know when it's done.
Thanks.

**Comment by clems4ever** [comment]
Hello @szimszon , I created a new UI for Authelia and I handled the case of the browser not handling U2F. In that case, the option is not even shown to the end user. I let you test it.
In the meantime, I'm closing the issue. Re-open it if you have any issue.
