### ISSUE TITLE
Access privilege issue

### ISSUE THREAD

**Issue by jesus7br** [clems4ever/authelia#305]
Hi @clems4ever,

I am experiencing issues with the Getting started demo.

I am able to start all docker-based services, by running the script authelia-repo/scripts/example-dockerhub/deploy-example.sh, and I also can enter the first factor when I try to log in.

However, when I am obtaining the token of the second factor, using Google authenticator, I can log in, but when I try to access some of the suggested pages (https://public.example.com:8080/ , https://dev.example.com:8080/users/john/secret.html , etc) it says that I don't have enough privileges to see the page.

I am using Ubuntu as OS and deploying Authelia using Docker. Could you provide me some starting point for troubleshooting this?

Thank you very much!

![screen shot 2018-12-10 at 16 36 31](https://user-images.githubusercontent.com/45764615/49743015-160e5000-fc9a-11e8-8c30-fc23504da63a.png)

**Comment by clems4ever** [comment]
Hello @jesus7br , thank you for reporting this bug. This documentation has been recently updated so I guess I missed something. I will try to reproduce and I'll let you know when it's fixed.

Thanks.

**Comment by clems4ever** [comment]
Hello @jesus7br , Authelia and the documentation has recently improved. Can you please retry the getting started doc now? Please reopen the issue if you still face any issue. Thanks.
