### ISSUE TITLE
Ability to read session secret from a file instead of specifying in the config file

### ISSUE THREAD

**Issue by leodotcloud** [clems4ever/authelia#310]
During the launch of Authelia in Kubernetes, the config is stored in a config map and injected into the container. The session secret is currently stored as part of the config map in clear. Having an ability to add a secret location instead, would allow us to store the session secret in a k8s secret and inject the path in the config file.

Context: https://github.com/rancher/charts/pull/93

**Comment by clems4ever** [comment]
Hello @leodotcloud , thank you for reporting. Unfortunately I did not invest a lot of time to tune Authelia for Kube yet but I appreciate very much your feedback. I will have a look to see if I can do something about it quickly.

Thanks.

**Comment by goniko** [comment]
There are a few other credentials currently sitting in the single config file that would benefit from this (e.g. for ldap, smtp...). So an alternative could be to allow specifying multiple config files as arguments (e.g. node server/src/index.js config1.yaml config2.yaml secret1.yaml secret2.yaml ...). People could then separate the configuration in whatever way fits their needs. If the same piece of configuration was specified in a few places, the last specified one would win. Now I'm not a JS expert, but perhaps something like https://github.com/TehShrike/deepmerge could be used.

**Comment by goniko** [comment]
I guess the downside would be that secrets would have to be wrapped with labels, which makes it a bit awkward, e.g.
session:
  secret: my-secret

**Comment by aroberts** [comment]
This may have been fixed by 80b1428849d522f6aba2dbd0b92735b5016c8e0a, depending on your specific needs

**Comment by clems4ever** [comment]
Indeed, @aroberts is right, that commit should do the trick.

**Comment by aroberts** [comment]
This appears to no longer work in v4, can we reopen?
