### ISSUE TITLE
Looking for maintainer of k8s chart in Rancher catalog

### ISSUE THREAD

**Issue by leodotcloud** [clems4ever/authelia#311]
I have created the initial version of the chart for Authelia. I am looking for another maintainer to review and help improve the chart going forward. Help is appreciated!

Please feel free to review this PR as well: https://github.com/rancher/charts/pull/93

**Comment by clems4ever** [comment]
Hello @leodotcloud , I can be the maintainer of this chart but I'm wondering if I'll be able to test the chart against your infrastructure without a paid plan. Do you know if we could sort this out?

Thanks.

**Comment by leodotcloud** [comment]
@clems4ever Rancher is 100% open source software. You can test/run the whole thing on your laptop or VM.

Docs for the simplest install: `https://rancher.com/docs/rancher/v2.x/en/installation/single-node/`

Also, if you prefer, please ping me on [Slack](https://slack.rancher.io) and I can unicast my setup details with you.

**Comment by clems4ever** [comment]
I will have a look at Rancher when I have a bit of time and I'll ping you afterwards. Thanks for the info in the meantime.

**Comment by clems4ever** [comment]
Authelia repository will embed its own chart based on this version: https://github.com/clems4ever/authelia/pull/458. It will soon be merged for v3 and will be updated for v4.

**Comment by clems4ever** [comment]
Please follow up on the subject with issue #274
