### ISSUE TITLE
Can authelia redirect to a different login hostname?

### ISSUE THREAD

**Issue by darkquasar** [clems4ever/authelia#313]
Hi I was wondering whether Authelia can redirect my login to "login-kb.example.com" instead of "login.example.com", is this possible?

Regards,
Diego

**Comment by clems4ever** [comment]
Hello @darkquasar , sure you can configure whatever domain name you want. Make sure the Authelia conf is in sync though.

**Comment by darkquasar** [comment]
Hi mate, sorry, I solved this 2min after I asked the question and forgot to edit it. It was a simple as changing the NGINX server configs. Thanks!

**Comment by clems4ever** [comment]
Good! thank you for letting me know. I'm closing the PR then.
