### ISSUE TITLE
Nothing on /

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#32]
Currently there's nothing on /. How about adding an default route that sends user to /login if not authenticated?

I've temporarly solved this with nginx and:
```
    location / {
        proxy_set_header  X-Original-URI $request_uri;
        proxy_set_header  Host $http_host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_pass http://auth/;
        rewrite ^/$ /login redirect; break;
    }
```

However if an default route existed I could drop my backend NGINX proxy all together in favor of my frontend proxy [Træfik](https://traefik.io/)

Currently I have Træfik-->NGINX-->Authelia, but with this fix I could Træfik-->Authelia. Big wins 😸

**Comment by clems4ever** [comment]
Hello @jkaberg , I don't really understand, can't you do the config with Traefik like you would with nginx. Is Traefik so limited?

**Comment by jkaberg** [comment]
I can't do the rewrite with Træfik,
```
rewrite ^/$ /login redirect; break;
```
Otherwise in my opinion Træfik is quite powerfull, but it's lacking fine grained controll like the above

**Comment by clems4ever** [comment]
Hello @jkaberg,

I found the following configuration snippet in the documentation of traefik.
Would not it work in your case to remove nginx?

# To redirect an entrypoint rewriting the URL:
# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#       regex = "^http://localhost/(.*)"
#       replacement = "http://mydomain/$1"
#

**Comment by SerialVelocity** [comment]
It seems like it can be done in Traefik directly. I think @jkaberg's original point is still valid though that `/` should redirect somewhere. `/login` seems like a reasonable choice.

Sorry, reason why I kind of hijacked this thread just now was to actually ask:
@jkaberg How would you get rid of nginx? I didn't think auth was configurable in Traefik (there only seems to be basic and digest auth)

**Comment by jkaberg** [comment]
@clems4ever yes thats true. however it would be better if Authelia did it instead. 

@SerialVelocity I didn't get rid of NGINX just yet, it still sits infront of the real servers using auth_request to send stuff to authelia. There is some work beeing done on this front,

**Comment by clems4ever** [comment]
FIY, I'm currently reworking the routes and I will serve the login page on / in the next version. It will be simpler. @jkaberg , I'll keep you posted once done.
