### ISSUE TITLE
BasicAuth for Blackbox in K8s

### ISSUE THREAD

**Issue by RafalMaleska** [clems4ever/authelia#324]
Hi, 

im trying to monitor http services protected by authelia (single factor). Those services run behind a nginx ingress controller in k8s. 

When using Blackbox (which enables only basic authentication) I'm always stuck on authelia (no rediraction to the service possible). 

Are You planing to implement the basic auth feature in next release?

**Comment by clems4ever** [comment]
Hello, @RafalMaleska , the basic auth feature is already implemented in Authelia.

**Comment by clems4ever** [comment]
Please open a new ticket with the error if you have an issue with the feature.
