### ISSUE TITLE
HashGenerator returning different hashes for same password

### ISSUE THREAD

**Issue by SBado** [clems4ever/authelia#332]
The situation:
I'm using an application on my phone to access a service, exposing an API, hosted on my pc behind Authelia. The service is protected with single factor authentication and the application is sending username and password in the requests' headers (basic authentication).

The problem:
The application is sending multiple requests in a very short period of time and this is causing an error inside the HashGenerator class. To see what happens, you can try the following code where a loop is simulating multiple requests happening "at the same time":

```
const crypt = require('crypt3/q');
for (var i = 0; i< 5; i++) {
    crypt('ds7K903h&$l="bHG', '$6$rounds=500000$Hnjso74lkOp9NhGG').then(function (hash) {
        console.log(hash);
    });
}
```

You will see that 5 different hashes will be generated. Of course, this causes the authentications to fail even if username and password are correct. On the other hand, bcrypt is working correctly (I know, unfortunately it's not SHA-512), and this is the reason why I think crypt may be the main culprit:

```
const bcrypt = require('bcrypt');
const myPlaintextPassword = '&T$3AUEoySOvf8!n6n0r';
for (var i = 0; i< 5; i++) {
    bcrypt.hash(myPlaintextPassword, '$2b$10$tQeQK.wj4i1BSAr4PWk9zO', function(err, hash) {
        console.log(hash);
        bcrypt.compare(myPlaintextPassword, hash, function(err, res) {
            console.log(res);
         });
    });
}
```
Authelia version is v3.12.0, node version is v8.15.0.

**Comment by clems4ever** [comment]
Hello @SBado , I think crypt is working correctly. You need to set a salt to have the same hash generated everytime as described in this thread: https://unix.stackexchange.com/questions/187333/why-mkpasswd-m-sha-512-produce-different-result-every-time-it-is-called.
Please re-open the ticket if this does not help. Thanks.

**Comment by SBado** [comment]
Hello @clems4ever, thank you for your response. The fact is that I am using a salt (second parameter: $6$rounds=500000$Hnjso74lkOp9NhGG) and it's the same salt for each call, so given the same password I should get the same hash, am I right?
Also, I took this code directly from the HashGenerator class (yes, I modified it a bit to get rid of the dependency from Bluebird), so if you see something wrong here maybe there's also something wrong in that class.

**Comment by clems4ever** [comment]
Hello @SBado, what you referring to is known as the number of rounds, not the salt. This doc explains it: https://passlib.readthedocs.io/en/stable/lib/passlib.hash.sha256_crypt.html

Please use the generator provided in authelia. `npm run hash-password mypassword`, Theresa are options fo the number of rounds and the salt. You can take a look at the code available in the `scripts` directory in `authelia-scripts-hash-password`.

**Comment by SBado** [comment]
I'm sorry, maybe I cannot explain myself. I don't need a way to generate a hash (I already used the script to generate the hashes for my users), my problem is the fact that Authelia CANNOT handle multiple requests at the same time.
Let me post the code Authelia is using to calculate the hash:

```
import BluebirdPromise = require("bluebird");
import RandomString = require("randomstring");
import Util = require("util");
const crypt = require("crypt3");

export class HashGenerator {
  static ssha512(
    password: string,
    rounds: number = 500000,
    salt?: string): BluebirdPromise<string> {
    // $6 means SHA512
    const _salt = Util.format("$6$rounds=%d$%s", rounds,
      (salt) ? salt : RandomString.generate(16));

    const cryptAsync = BluebirdPromise.promisify<string, string, string>(crypt);

    return cryptAsync(password, _salt)
      .then(function (hash: string) {
        return BluebirdPromise.resolve(Util.format("{CRYPT}%s", hash));
      });
  }
}

```

The cryptAsync method is taking two arguments, the password and the salt, just like the function I posted. They are the same functions, yours is using the sync version of crypt (promisified via Bluebird) while mine is using the async one, but they are exactly the same. I put some print in your code to check which salt was used in the requests generated from the app on my phone and I used the same salt in the example I posted in my previous post (as I said, it's $6$rounds=500000$Hnjso74lkOp9NhGG, which clearly isn't the number of rounds simply because it is not a number but a string. This is the SALT I and Authelia are using to generate the hashes).
This code (the Authelia code) gives different hashes for the same password IF a new request arrives while the promise (cryptAsync) has not yet been resolved. You can test it yourself with a simple script with a curl request (curl -u authelia_user:authelia_pass https://path/to/my/service): try to call it more than once at the same time (they have to run in parallel, not one after the other) and you will see what I'm talking about. Authelia will tell you that user and password are wrong even if they aren't.

Did you try to run the simple example I posted? It's a one minute test, you can copy and paste it inside a file an run it with node. There's definitely a problem on crypt side, if you will try you will see it.

**Comment by clems4ever** [comment]
@SBado , do you use a LDAP server or a file based user database?

**Comment by SBado** [comment]
@clems4ever I use file based user database

**Comment by clems4ever** [comment]
Hello @SBado , while searching on the web I found out the man of crypt on Unix and I think I found the issue you're facing: https://linux.die.net/man/3/crypt_r. Authelia is probably using the no-reentrant version of crypt while it should use crypt instead.
I will check how I can confirm and fix that.

**Comment by clems4ever** [comment]
Confirmed: https://github.com/sendanor/node-crypt3/blob/a83803f87f2c23a12c383061c4163b72dbf212fc/crypt3.cc#L24

**Comment by SBado** [comment]
@clems4ever thank you for investigating!
In the meantime, if you like, I can provide you some small patches to include support for bcrypt (they not force you to use bcrypt, crypt support is still included). Let me know if you are interested.

**Comment by clems4ever** [comment]
Hello @SBado , if you can still wait a couple days you will be a beta tester of version 4 of Authelia. I'm rewriting the app in Go and the issue should be resolved in that new version since I use the reentrant version of crypt already.
New features in version 4: big bump of performance (still to be measured), security enhancement regarding the identity verification using JWT tokens and bump of the version of U2F on server side to target v1.1 of the protocol for detecting clones of security keys.

**Comment by SBado** [comment]
No problem, I can wait as long as you need, my system is working perfectly fine at the moment. I didn't know about the rewrite in Go, that's the reason why I proposed you my simple patches. Take your time and keep going with your great work!

**Comment by clems4ever** [comment]
Here we go, the Go version is going to be released in beta in the coming days. Do you think you can help testing on that version in master?

**Comment by SBado** [comment]
As I think you already know by now, I'm already testing it and it's working great!

I'm closing this issue, thank you.

**Comment by clems4ever** [comment]
Great news!
