### ISSUE TITLE
[Question]: ssh pam module integration?

### ISSUE THREAD

**Issue by davama** [clems4ever/authelia#335]
Hello @clems4ever 

First off, thank you very much for the awesome project!
It seems like it has been getting more attention recently, which is a good thing.

I am sure this is outside of the scope of this project but curious to your thoughts/opinion on this.

I had tried DUO products which offer something similar to this project but they did not support openldap with rfc2307bis schema for whatever reason, nor do they have plans to integrate.  I really like them, especially the push notification feature but it was not going to work out...

Currently we use [google-authenticator pam module](https://github.com/google/google-authenticator-libpam) and are looking to see if we could have one TOTP for ssh shell access and  web services.

One of my ideas was to do a 'hacky' script which would pull the secret from mongodb and replace it on each user's secret file that way google pam would use the secret file that also exist in mongodb.

Hope im making sense.

Thank you again for your support!

Best,
Dave

**Comment by clems4ever** [comment]
Hello @davama , glad you like Authelia! Indeed, your idea is a bit hacky since you would not even need Authelia to make it work, you only need a secret store. Integrating Authelia with PAM was not planned but it could actually be a good idea. I don't know yet how it would look like though (Open a browser to pass the factors? Get a token from the web?).

What are your requirements? For instance with my servers I use a U2F device as a private key holder and integrate it with gpg-agent to login. So when I want to access my server, I plug my key, run the ssh command and then I need to type a PIN for the key to be unlocked and the server to let me in. Wouldn't it be a solution for you?

**Comment by davama** [comment]
Thank you for the response. 

> Indeed, your idea is a bit hacky since you would not even need Authelia to make it work, you only need a secret store. 

Technically, with this pam module, it would not need it. Only to retrieve the latest secret and store in a [file](https://github.com/google/google-authenticator-libpam/blob/60207b6c4cebf825863043e963bf67f6a0520076/src/pam_google_authenticator.c#L57).

>Integrating Authelia with PAM was not planned but it could actually be a good idea. I don't know yet how it would look like though (Open a browser to pass the factors? Get a token from the web?).

The factor is passed to the [terminal](https://github.com/google/google-authenticator-libpam/blob/60207b6c4cebf825863043e963bf67f6a0520076/src/pam_google_authenticator.c#L58), which then does its calculations.

I've been reading up on building pam modules, hoping to use that as a template but changing the source of the secrets to the mongodb.

> What are your requirements? For instance with my servers I use a U2F device as a private key holder and integrate it with gpg-agent to login. So when I want to access my server, I plug my key, run the ssh command and then I need to type a PIN for the key to be unlocked and the server to let me in. Wouldn't it be a solution for you?

Currently no, since 2nd factor is our mobile device which everyone always carries...convenient.

We are simply trying to unify web login TOTP and ssh shell access TOTP with one TOTP. 

Of course it was not in the pipeline of this project but simply asking :smile: 

Thanks again!

**Comment by clems4ever** [comment]
Hey, just wanted to let you know that I've just added support for Duo push notifications. It might be of interest to you :).
