### ISSUE TITLE
Tag docker builds

### ISSUE THREAD

**Issue by SerialVelocity** [clems4ever/authelia#34]
Hey!

Love the work you're doing here! Is it possible to tag the docker builds with version tags? It would be nice to not be restricted to just `latest` which can vary on different machines depending on when you last ran a `docker pull`.

Cheers,
Ben

**Comment by jkaberg** [comment]
Docker Hub can be setup to build images from Github tags, https://docs.docker.com/docker-hub/builds/#add-and-run-a-new-build 😄

**Comment by clems4ever** [comment]
Definitely, I will change the Travis deployment to tag the images with the git tags. It should be done today, I'll keep you posted.

**Comment by clems4ever** [comment]
Hello @SerialVelocity  , it's done. Docker images are now tagged with npm versions.

**Comment by SerialVelocity** [comment]
Nice! Thank you!
