### ISSUE TITLE
Strange ~1min delay on pending resources behind proxy

### ISSUE THREAD

**Issue by JCBird1012** [clems4ever/authelia#359]
I've been encountering an interesting 60 second delay on loading resources secured behind Authelia. I'm fairly certain that this isn't an issue with Authelia itself (I encountered a very similar issue using [Vouch](https://github.com/vouch/vouch-proxy) but I could never narrow it down)...

<img width="1680" alt="Screen Shot 2019-04-23 at 17 14 29" src="https://user-images.githubusercontent.com/5911308/56616819-4c66bf00-65ec-11e9-8b01-a6f814e7b85f.png">

Notice how it's only certain resources — that's what makes this even more bizarre.

I know it likely isn't an issue with the backend service itself, because once I reconfigure Nginx to disable Authelia securing that backend, **everything works**. Switching to something like ```http_basic_auth``` or just unsecuring the endpoint makes everything work at normal speed once again.

I'm not doing any rewriting of headers or much else outside of the config I've shown below (besides configuring TLS which I think doesn't impact this issue at all).

This happens no matter which browser I use.

Here's my Authelia endpoint config: 
```
server {
    listen [::]:443 http2;
    server_name authelia.$MYDOMAIN.com;
    include tls.conf;
    send_timeout 100m;

    set $upstream http://$AUTHELIA_ENDPOINT:9091;

    # Serves the portal application.
    location / {
       proxy_pass        $upstream/index.html;
    }

    location /static {
        proxy_pass        $upstream;
    }

    # Serve the backend API for the portal.
    location /api {
        proxy_set_header  X-Real-IP $remote_addr;

        # Required by Authelia because "trust proxy" option is used.
        # See https://expressjs.com/en/guide/behind-proxies.html
        proxy_set_header  X-Forwarded-Proto $scheme;

        # Required by Authelia to build correct links for identity validation.
        proxy_set_header  X-Forwarded-Host $http_host;

        # Needed for network ACLs to work. It appends the IP of the client to the list of IPs
        # and allows Authelia to use it to match the network-based ACLs.

        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_intercept_errors on;
        proxy_pass        $upstream;
    }
}
```
and the configuration for the endpoint I'm trying to secure:

```
server {
    listen [::]:443 http2;
    server_name $SERVICE.MYDOMAIN.com;
    include tls.conf;
    send_timeout 100m;

    #Websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    location / {
    set $upstream http://$SERVICE_BACKEND:$SERVICE_PORT;
        proxy_pass $upstream;

    auth_request /auth_verify;

    set $target_url $scheme://$http_host$request_uri;
        error_page 401 =302 https://authelia.$MYDOMAIN.com/#/?rd=$target_url;

        proxy_set_header Proxy-Authorization $http_authorization;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

   # Virtual endpoint forwarding requests to Authelia server.
        location /auth_verify {
            internal;
            proxy_set_header            X-Real-IP $remote_addr;

            # Provide either X-Original-URL and X-Forwarded-Proto or
            # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
            # Those headers will be used by Authelia to deduce the target url of the user.
            #
            # X-Forwarded-Proto is mandatory since Authelia uses the "trust proxy" option.
            # See https://expressjs.com/en/guide/behind-proxies.html
            proxy_set_header            X-Original-URL $scheme://$http_host$request_uri;

            proxy_set_header            X-Forwarded-Proto $scheme;
            proxy_set_header            X-Forwarded-Host $http_host;
            proxy_set_header            X-Forwarded-Uri $request_uri;

            proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;

            # Authelia can receive Proxy-Authorization to authenticate however most of the clients
            # support Authorization instead. Therefore we rewrite Authorization into Proxy-Authorization.
            proxy_set_header            Proxy-Authorization $http_authorization;

            proxy_pass                  https://authelia.$MY_DOMAIN.com/api/verify;
        }

}
```

Of course, substituting in the variable values with real values.

This issue looks strangely similar to [this one](https://stackoverflow.com/questions/12606898/mysterious-1min-delay-in-http-post-between-browser-and-nginx), and is always roughly consistent around 1 minute (which leads me to believe something is timing out somewhere).

I've played with ```Content-Length``` headers,  adding ```Host``` headers with no luck. This happens on many of my backends.

**Comment by JCBird1012** [comment]
I think I've figured it out. 

Apparently, proxying the ```auth_request``` out to the Internet and hitting my domain externally wasn't making Nginx happy — changing the line from ```proxy_pass                  https://authelia.$MY_DOMAIN.com/api/verify;``` to ```proxy_pass                  https://authelia:9091/api/verify;``` so that it is internally routed within the Docker network I have configured makes it work normally.

**Comment by clems4ever** [comment]
Hello @JCBird1012 , great you found that out :).
