### ISSUE TITLE
Authelia and LDAP bad gateway

### ISSUE THREAD

**Issue by tcheronneau** [clems4ever/authelia#362]
Hello,

I've some issues with my setup. 
So I'm running authelia in docker with the official image (v3.13 for now). 
My infrastructure is under kubernetes with traefik as ingress controller. 
I'm currently using the file backend for my user and wanted to migrate to LDAP. 
With file as backend everything is fine. 
When I'm using LDAP I get a 502 in traefik logs : "POST /api/firstfactor HTTP/2.0" 502 11 "https://authdev.mcth.fr/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0" 2235 "authdev.mcth.fr" "http://10.244.4.51:8080" 120003ms

I'm guessing the issue in under my LDAP configuration but I can't find my error. 
My LDAP is working (I'm using it for grafana and gitea for example). 

Here is my configuration : 
`authentication_backend:
  ldap:
    # The url of the ldap server
    url: ldaps://myldapurl
    insecure: true

    # The base dn for every entries
    base_dn: dc=domain,dc=tld

    # An additional dn to define the scope to all users
    additional_users_dn: cn=users

    # The users filter used to find the user DN
    # {0} is a matcher replaced by username.
    # 'cn={0}' by default.
    users_filter: uid={0}
    #users_filter: cn={0}

    # An additional dn to define the scope of groups
    additional_groups_dn: cn=groups

    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # 'member={dn}' by default.
    groups_filter: (memberUid={dn})
    #groups_filter: (memberUid={0})

    # The attribute holding the name of the group
    group_name_attribute: cn

    # The attribute holding the mail address of the user
    mail_attribute: mail

    # The username and password of the admin user.
    user: ldap_user
    password: very_secure_pass`

I've added a parameter I've found in the code not sure it's really working (insecure) since my ldap is with untrusted cert. 

If you can help me with that I don't see my mistake. 
Thanks.

**Comment by clems4ever** [comment]
Hello @tcheronneau , nice try the `insecure: true`. Unfortunately this is not yet supported because this key is not even read by Authelia. I'll be working on connecting all backends over TLS soon though.

Do you have some logs from Authelia so that I can assist further?

**Comment by tcheronneau** [comment]
Hi @clems4ever thanks for the answer. 
Unfortunately no there is no logs except the one from Traefik. 
Authelia does not even see that there was an error. 
I've tried to do a tcpdump and my container does try and seems to succeed to do exchange with my ldap server. But indeed without logs it's a bit hard to debug. 
Even in debug I've got nothing. The last log is : 
`debug: LDAP: Bind user 'myldap_user'`

Did you said that TLS is not implemented ? So maybe it's because it's not try to reach the port 636 ?

**Comment by tcheronneau** [comment]
@clems4ever I've write a bit of code even if it's not my thing and I manage to fix the issue.
So from what I've modified the issue seems to be the certs which is not valid. 
I close the issue since it's just my implementation which is not working. 
Thanks again.

**Comment by tcheronneau** [comment]
I would be pleased to do a PR but I'm really not a dev and don't want to make it worse. 
But from what I understood (I don't know nodejs) you retrieve the variable for ldap in src/lib/ServerVariablesInitializer.js and so you could add the insecure variable like that (in file src/lib/authentication/backends/ldap/connector/Connector.js) : 
`
        const ldapClient = ldapjs.createClient({
            url: url,
            tlsOptions: {
              rejectUnauthorized: insecure
            },
            reconnect: true
        });
` 
For me it will do the trick

**Comment by clems4ever** [comment]
Alright, I see. Let's keep the code as it is for the time being since a new major version will come soon.
