### ISSUE TITLE
Second factor page displaying broken iframe on Firefox

### ISSUE THREAD

**Issue by tpansino** [clems4ever/authelia#363]
After authenticating with username/password, I see this in Firefox on the second factor page:
![Screenshot from 2019-05-07 21-15-05](https://user-images.githubusercontent.com/2768420/57352200-85894e00-7119-11e9-9ae4-17c185a7b5b7.png)

It looks like Firefox isn't able to understand the `chrome-extension` iframe, so it displays an error in the iframe.

**Comment by clems4ever** [comment]
Hello @tpansino , what version of Firefox do you use?

**Comment by tunip** [comment]
Hello, same iframe on second factor page. I use Firefox 66.0.5 (64-bit)

**Comment by tpansino** [comment]
@clems4ever Version 66.0.5 (64-bit), same as @tunip. I also think version 65 had it as well.

**Comment by clems4ever** [comment]
It's weird, I cannot reproduce with 66.0.3 (64-bit). I thought I had solved that issue a while ago... I will continue to search what it can be due to. My guess right now is that I have something installed on my laptop that you guys don't have. I need to figure out what.

I'll let you know if I find something.

**Comment by clems4ever** [comment]
Do you use the latest version of Authelia?

**Comment by tunip** [comment]
I use version 3.15.0 installed via npm.

**Comment by tpansino** [comment]
I'm using `image: clems4ever/authelia:latest` in my `docker-compose.yml` file.

I tested it with all Firefox add-ons disabled and was still able to reproduce the issue. @clems4ever, you might try the "Restart with Add-ons Disabled" option as well, see if that helps you.

**Comment by clems4ever** [comment]
Thanks @tpansino , did not know that option, I will have a look.

**Comment by clems4ever** [comment]
I've just tried and I still don't reproduce. That's weird. Do you have the the config flag: "security.webauth.u2f" disabled or enabled? What if you toggle it? You need to access "about:config" to do so.

**Comment by tpansino** [comment]
Ah yes, `security.webauth.u2f = false` in my `about:config` (which is the default).

Toggling it to `true` does resolve the issue. So I guess there needs to be a fix around that setting?

**Comment by clems4ever** [comment]
I guess there should be a fix indeed but I've not found it yet unfortunately. I'm still actively looking for it though.

**Comment by tpansino** [comment]
@clems4ever it looks like Firefox now defaults `security.webauth.u2f = true`, at least as of version 67. That makes this issue less significant since most people won't change defaults and notice it.

Do you still want to leave this open to eventually find a fix?
