### ISSUE TITLE
URLs in E-Mails Not Working

### ISSUE THREAD

**Issue by n4kre** [clems4ever/authelia#365]
Hi @clems4ever,

I am experimenting version 3.15.0 of Authelia, and it looks like the URLs embedded in e-mails point to invalid locations: they result in an HTTP status 404.

Sample affected URLs – parameters are truncated:
- `https://login.example.com/one-time-password-registration`;
- `https://login.example.com/security-key-registration`;
- `https://login.example.com/reset-password`.

For your reference, I am using the following [Nginx configuration](https://github.com/clems4ever/authelia/issues/364#issue-442113138).

**Comment by clems4ever** [comment]
This is weird, this URL is produced by https://github.com/clems4ever/authelia/blob/8478216e5d392a379ff1b4a2f22b097aae16d391/server/src/lib/IdentityCheckMiddleware.ts#L118. We clearly see that `/#/` is a constant in that URL.
Can the reverse proxy strip it in some way?

**Comment by clems4ever** [comment]
It's weird, this URL is normally produced by https://github.com/clems4ever/authelia/blob/8478216e5d392a379ff1b4a2f22b097aae16d391/server/src/lib/IdentityCheckMiddleware.ts#L118.
Can the reverse proxy strip it in some way?

**Comment by n4kre** [comment]
Directly fetching the link received via e-mail without going through any reverse proxy:

```bash
$ wget -qSO- 'http://127.0.0.1:4221/one-time-password-registration?token=Ch0RyTELuPF10Os9uKCPrbrVhYiVjUONmZqj5qkSOqiXiNriWYJP7lD8DTucACf1'
  HTTP/1.1 404 Not Found
  X-Request-Id: 7427a2ca-8c41-4f1b-8fb8-429938937f1e
  X-DNS-Prefetch-Control: off
  X-Frame-Options: SAMEORIGIN
  Strict-Transport-Security: max-age=15552000; includeSubDomains
  X-Download-Options: noopen
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  Content-Security-Policy: default-src 'self'
  Content-Type: text/html; charset=utf-8
  Content-Length: 169
  Date: Thu, 09 May 2019 09:32:52 GMT
  Connection: keep-alive
```

The corresponding log entry is:

```syslog
May 09 11:32:52 abricot index.js[2417]: debug: date='Thu May 09 2019 11:32:52 GMT+0200 (CEST)' method='GET', path='/one-time-password-registration' requestId='7427a2ca-8c41-4f1b-8fb8-429938937f1e' sessionId='lawNimWYhFU1KChVe6-FpvPS3b3ov-wv' ip='::ffff:127.0.0.1' message='Headers = {"user-agent":"Wget/1.19.4 (linux-gnu)","accept":"*/*","accept-encoding":"identity","host":"127.0.0.1:4221","connection":"Keep-Alive"}'
```

**Comment by jmccoy555** [comment]
I think I'm getting this too (with 3.15.0 and 3.16.0), 

`https://undefined/#/one-time-password-registration?token=sbLsKsNesZZoJNDcDode0M9GbEAhe4grH4DDDpMR8EfswqY3eirBeQouxAXHjb4j`

If I manually change  `undefined` to the correct address everything works perfectly.

**Comment by clems4ever** [comment]
The X-Forwarded-Host and X-Forwarded-Proto are missing. Those headers needs to be provided in requests reaching Authelia. That's what's used to build the URL.
