### ISSUE TITLE
no dockerhub found on numerous attempts at building

### ISSUE THREAD

**Issue by cxgl** [clems4ever/authelia#382]
Hi,

I seem to be having a problem building/running authelia. My intention is to use it with our nginx server and samba4/ldap as a backend.

I have a pristine, new docker installation on debian 9. I've installed build-essentials, docker-compose, node (I've tried versions 12, 10, and 8 to the same effect), and node.js.

I git clone, then source bootstrap.sh -- all seems to work fine (except for node v12 -- crypt3 doesn't like v12), but when I run: authelia-scripts suites start dockerhub

I only get: [WARNING] This suite does not exist. Use 'list' command to check the existing suites.

Listing only shows:
```
basic
basic-bypass-no-redirect
duo-push
high-availability
kubernetes
network-acls
short-timeouts
traefik
```
Can anyone point me in the right direction, please?

**Comment by clems4ever** [comment]
Hello @cxgl , the suite has been removed recently. Did you find the command somewhere in the doc? Can you point me to it so that I can remove it? Thanks.

**Comment by cxgl** [comment]
Thank you, Clément.
When done building, it says:
`2019-07-15 11:39:54 (17.3 MB/s) - ‘/tmp/kubectl’ saved [39214560/39214560]

[BOOTSTRAP] Run 'authelia-scripts suites start dockerhub' to start Authelia and visit https://home.example.com:8080.
[BOOTSTRAP] More details at https://github.com/clems4ever/authelia/blob/master/docs/getting-started.md
(authelia) root@cxdocker01:/home/minion/authelia# authelia-scripts suites start dockerhub
[WARNING] This suite does not exist. Use 'list' command to check the existing suites.
`

...so I guess in bootstrap.sh?

The question is, then -- what to do next? I mean I can start "basic", which shows me a blank portal (i.e.: only says SIGN IN with nothing else) at http://(docker server):3000, but that's it.

**Comment by clems4ever** [comment]
well, the dockerhub suite would have given you the same result. You should try to use the high-availability suite instead, the permissions displayed in https://home.example.com:8080 do match this environment.

I will update the bootstrap.sh script. Sorry for that.

**Comment by cxgl** [comment]
Thanks, Clément.
I tried high-availability, and get the same thing -- just a dialog on the web page that says 'authelia', but nothing else. No edit boxes for anything.

I do seem to get this on the docker app start:
`Error: Cannot find module '/home/minion/authelia/server/src/lib/configuration/Configuration.schema.json'`
Could that be why it's blank?

**Comment by jumblies** [comment]
same thing here.  deleted directory and did a fresh pull.

**Comment by clems4ever** [comment]
In v4 a new "docker-image" suite has been provided, equivalent of dockerhub one except this one does not rely on previous version of Authelia pushed to Dockerhub but on a locally built image of Authelia.
