### ISSUE TITLE
Registering a new device results in potentially harmful advice

### ISSUE THREAD

**Issue by naggie** [clems4ever/authelia#386]
If a user logs in via the first factor, LDAP, and then attempts to register a new device the following email is received:

image](https://user-images.githubusercontent.com/208440/62050855-fe281400-b209-11e9-8713-9df5284b5bce.png)

Note the advice:

>  _Please ignore this email if you did not initiate the process._

If the user did not attempt to register a new device, this implies an attacker has compromised the first factor. I argue that the user probably shouldn't ignore the email because of this.

Do you think the advice should be changed to a warning?

**Comment by clems4ever** [comment]
Hello @naggie , please note that the token to perform the action (reset password or register a device) has a TTL of 5 minutes (https://github.com/clems4ever/authelia/blob/fbe7b77bcee49bdb88ccbd5d5fb650c0a2c64b84/server/src/lib/IdentityCheckMiddleware.ts#L24) but I agree that it's reasonable to tell her to change her credentials and/or contact the admin instead.

**Comment by naggie** [comment]
I was aware of that -- I wasn't referring to the ability of an attacker to use an old token, rather the fact that a user may not realise their first-factor has been compromised.

Thanks!

**Comment by clems4ever** [comment]
Hello @naggie , would #400 fix the issue?

**Comment by naggie** [comment]
Definitely. Thanks!
