### ISSUE TITLE
Duo not working

### ISSUE THREAD

**Issue by numin0us** [clems4ever/authelia#393]
I'm trying to use Duo Mobile with Authelia and I am not seeing any option available to use it. I can log in successfully using TOTP but no option to use Duo is available. 

Here are some relevant sections of my config 
```
totp:
  issuer: xxx.xxx

duo_api:
    hostname: api-xxx.duosecurity.com
    integration_key: xxx
    secret_key: xxx

...
access_control:
  default_policy: deny

  rules:
    - domain: xxx.xxx.xxx
      subject: group:admin
      policy: two_factor

```
I don't see any Authelia debug logs which indicate interaction with the Duo backend, it seems to just go directly to prompting for a TOTP. I can post sanitized logs if it'll help provide context.

**Comment by codefriar** [comment]
I'm experiencing the same issue.  Here's what I found in my logs:

```
debug: date='Tue Sep 10 2019 14:16:13 GMT+0000 (UTC)' method='POST', path='/api/duo-push' requestId='5222a455-23b2-4ca4-b009-f2c77bfcf06e' sessionId='9R0W36tbmi-ki9A4MnYJWMDnK-xOzS' ip='10.0.1.1' message='TypeError: Cannot read property 'result' of undefined,
    at fulfilled (/usr/src/server/src/lib/routes/secondfactor/duo-push/Post.js:4:58),
    at process._tickCallback (internal/process/next_tick.js:188:7)',
    at <anonymous>,
    at Generator.next (<anonymous>),
    at /usr/src/server/src/lib/routes/secondfactor/duo-push/Post.js:40:38,
error: date='Tue Sep 10 2019 14:16:13 GMT+0000 (UTC)' method='POST', path='/api/duo-push' requestId='5222a455-23b2-4ca4-b009-f2c77bfcf06e' sessionId='9R0W36tbmi-ki9A4MnYJWMDnK-xOzS' ip='10.0.1.1' message='Reply with error 200: Cannot read property 'result' of undefined',
debug: date='Tue Sep 10 2019 14:16:13 GMT+0000 (UTC)' method='POST', path='/api/duo-push' requestId='5222a455-23b2-4ca4-b009-f2c77bfcf06e' sessionId='9R0W36tbmi-ki9A4MnYJWMDnK-xOzS' ip='10.0.1.1' message='Header x-target-url is set to undefined'
```

**Comment by jmccoy555** [comment]
It's working for me; Nginx with Authelia Docker version tag 3.15.0

I think the first time I had to select 'use another method' then it remembered it as the default.

**Comment by codefriar** [comment]
Additionally, i'm not seeing any authentication *attempts* for the configured duo application in the DUO logs

<img width="1162" alt="Screen Shot 2019-09-10 at 11 39 09 AM" src="https://user-images.githubusercontent.com/642589/64628574-a0b5e400-d3bf-11e9-96f1-2bc381fdbdbe.png">

**Comment by codefriar** [comment]
> It's working for me; Nginx with Authelia Docker version tag 3.15.0
> 
> I think the first time I had to select 'use another method' then it remembered it as the default.

I'm using the standard node server via docker.

**Comment by cmschube** [comment]
Same issue here w/same codes/logs as @codefriar

**Comment by clems4ever** [comment]
My guess is the Duo API has changed. I'll have a look.

**Comment by jmccoy555** [comment]
Still working fine on 3.16.0

Let me know if you need any info, but my config looks the same to me;

```
totp:
  issuer: xxx.xxxxx
  
duo_api:
  hostname: api-xxxxx.duosecurity.com
  integration_key: xxxxxxx
  secret_key: xxxxxxxxxx

authentication_backend:  
  ldap: 
   all the ldap blah blah

access_control:
  default_policy: deny
  rules:
  - domain: intranet.xxxxx.xxxx
    subject: 'group:users'
    policy: two_factor
```

Only issue is the Duo app doesnt report my IP / Location and Target URL

**Comment by nightah** [comment]
Mine also appears to be working fine with `3.16.1` and has since it has been updated to include Duo.

**Comment by nightah** [comment]
Also @jmccoy555 that should have been added/fixed in https://github.com/clems4ever/authelia/pull/344. Per the screenshot I shared there, it still appears to be working for me.

**Comment by clems4ever** [comment]
Can you guys triple check your API keys and paste some logs if it's still not fixed for you? Thanks.

**Comment by clems4ever** [comment]
Any news? Please reopen the issue if you still need help to figure out why Duo is not working for you.
