### ISSUE TITLE
Authelia does not retrieve group information from an apaches server

### ISSUE THREAD

**Issue by igloves** [clems4ever/authelia#40]
Hi, 

I have testing authelia and have it working fine with the exception I cannot read group information from an apacheDS ldap server. If I set access control in the config template to set a default domain or to allocate a domain to a user specifically - all works fine. But not if I want to determine access via a group member.

Other LDAP attributes are returned just fine : dn mail etc

There are no error messages - by increasing the log level to debug and adding a few extra log entries I can see the group dn & query are al lconstructed correctly - just no data is ever returned.

Do you have any pointers ?

Thanks

**Comment by clems4ever** [comment]
Hello @igloves, I have never faced this issue. Can you please make sure the type of object for your groups in LDAP is the same as the one I defined in the file example/ldap/base.ldiff?

**Comment by igloves** [comment]
Hi @clems4ever 
The ldap is the same as your example. In fact I have run this against another directory IBM SDS and it works fine, the data is the same its been migrated from one to the other.  The problem is specific th apacheDS.
I have added a few debug statements and can see the  ldap filter is setup correctly but when the call is made to ldap.js:Ldap.prototype._search_in_ldap it never produces anything. 
I have written some call test code using ldapjs to do a client.search using the same filter and this works too.

**Comment by igloves** [comment]
Hi @clems4ever

I've tracked it down... The issue arises because there are ACLs applied to the apacheDS Im using which prevents the user from interrogating the group definitions. The ldap.js module assumes access and all functions are performed using the initial user bind. Logically I think this module should be split so that protected directories can be searched by a privileged user and the initial bind can be checked separately.

**Comment by clems4ever** [comment]
Hello @igloves , this is interesting! Do you have a Docker image of a LDAP like yours so that I can fix it and add an integration test to be sure the fix is working?

**Comment by clems4ever** [comment]
Hello @igloves , I created the branch **ldap-bind** to fix the issue.

**Comment by igloves** [comment]
No sorry. But I think you could still test with what you have just make sure the admin functions are performed by a configurable admin ID. I would be very happy to beta test this for you

**Comment by clems4ever** [comment]
Hello @igloves,

I'm setting up an env with ACL rules like yours to make a good fix and ensure non regression. I'll keep you posted when I have a good fix.

**Comment by clems4ever** [comment]
Hello @igloves , can you please test PR #45 with your Apache LDAP?
On my side I added custom ACL rules on the OpenLDAP server to restrict search operations for users and it seems to work.
Be careful, I changed the deployment commands to package everything better. Please read the **Getting started** section of the README to see.

**Comment by clems4ever** [comment]
Hello @igloves , any news? Just let me know if you don't have time to test it before I merge. I plan to merge the PR next week end.

**Comment by clems4ever** [comment]
Hello @igloves, I merged the PR into mainstream.
