### ISSUE TITLE
MongoClient DeprecationWarning

### ISSUE THREAD

**Issue by davama** [clems4ever/authelia#403]
Got interesting logs:

```
(node:31000) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:31000) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect.
```
Im looking around and suspect that this should be adjusted. 
https://github.com/clems4ever/authelia/blob/dd0add96186690e0a5c0696c9ac78e3670d08068/server/src/lib/connectors/mongo/MongoClient.ts#L25

If i am right, maybe to this?:
```
const options: MongoDB.MongoClientOptions = {
   useNewUrlParser: true,
   useUnifiedTopology: true
};
```
Was trying to test the above locally but maybe i was not building from local project. 

Either way after i edited `dist/server/src/lib/connectors/mongo/MongoClient.js` and included those options the logs went away...
```
	        const options = {
		    useNewUrlParser: true,
	   	    useUnifiedTopology: true
		};

```

Hope i did it right

Thanks!
Dave

**Comment by clems4ever** [comment]
Hello @davama , sorry I've been busy lately.
I think I'm not gonna do the fix you propose because I should come up with a Go version of Authelia very soon (couple of days). This will remove that issue but thanks for notifying.
