### ISSUE TITLE
Authelia behind nginx - behind nginx

### ISSUE THREAD

**Issue by mamema** [clems4ever/authelia#404]
Hi

as i'm not sure if it is a problem with nginx or authelia, i'm asking for help here.

As my Synology uses ngnix 1.15 without auth module compiled, i've created a docker vm with the official ngnix 1.17 with everything in it.

But now i have a good working and configured non auth nginx which runs in front of the docker ngnix with auth. On the same docker env (same host) the latest authelia is running.

I now forwarded proxy requests to the second reverse proxy.
I can auth with authelia without problems, if the domain is a sub domain like:

xxx.example.com

but i also want to auth my web sites with a base dir like:

www.example.com/subdir

this is not working because of  lack of understanding of nginx on my side i guess.
or is this just by design?

Can someone help me here with a working example for this use case?

**Comment by nightah** [comment]
What does your nginx config on both for the subdir look like?

A better way to achieve what you want would be to put your auth nginx in front of the other, making that your primary reverse proxy and routing to your synology nginx where required (presumably just for the synology based interfaces etc).

**Comment by mamema** [comment]
Synology needs to use 80/443 ports first and this cannot be changed. So your proposal wouldn't work. 
But i've helped myself with switching completely to subdomain instead of subdir. So can be closed.

**Comment by nightah** [comment]
Actually it doesn't need to, there are plenty of guides which tell you how you can safely disable it from blocking port 80/443.

Having said that glad you found an alternative solution.

**Comment by mamema** [comment]
Oh, really didn't found "plenty" of those and unfortunately not suiting to my setup. As i've tried to route the whole traffic through a docker nginx with auth, i discovered another downside of your approach.
As soon as dynamic realtime traffic is affected (eg guacamole remote desktop), then the docker network driver is too slow (by design), so network latency is very bad. Only "solution" then is to try MACVLAN solutions which at the end only work, if you havent virtual machine manager running. So.... welll :-)
Anyway, great solution to have authelia now.

**Comment by clems4ever** [comment]
Great you found a solution @mamema and thanks a lot for helping @nightah.
