### ISSUE TITLE
We should be able to use authelia with http

### ISSUE THREAD

**Issue by Nautigsam** [clems4ever/authelia#408]
I found the following line forcing the schema to be `https:` to make the redirection "safe":
https://github.com/clems4ever/authelia/blob/dd0add96186690e0a5c0696c9ac78e3670d08068/server/src/lib/utils/IsRedirectionSafe.ts#L9

I think it should be possible to use authelia with http for testing purpose.

**Comment by clems4ever** [comment]
Hello @Nautigsam , can you elaborate on what you're trying to test? I don't see what it can be since it's not possible to protect an http page with Authelia because the cookie is not sent over HTTP for security reasons.

**Comment by Nautigsam** [comment]
I was trying to test authelia in my dev environment where I don't use HTTPS. I am aware that it is not safe in production but it should be possible to still use HTTP for testing-purpose.

**Comment by clems4ever** [comment]
I understand the point but this is definitely not a priority in my backlog. Do you think you will be able to do a patch if we agree on the contract? Authelia is written in Go now.

**Comment by Nautigsam** [comment]
If it's written in Go then I can't do anything, I'm a total noob in this. Sorry.

**Comment by clems4ever** [comment]
So, I'll let people re-open this issue and do a PR if they want to implement it.
