### ISSUE TITLE
Creating a user with File provider

### ISSUE THREAD

**Issue by solipsist01** [clems4ever/authelia#409]
Perhaps a simple question, but,
How can i create a user in users_database.yml

I have seen the following example file.
https://github.com/clems4ever/authelia/blob/master/test/suites/basic/users_database.yml

Is this file editted manually?
I have seen in another issue in github that i can use scripts for generating the password hash.
However, the scripts don't appear to be present in the docker image

Thank you.

**Comment by zegerhoogeboom** [comment]
I had basically the same question recently and I ended up manually adding users into the file with an empty password (i.e. `password: ""`), giving users their username and asking them to do a password reset and the password will be hashed through the password reset. You do need to have a working notification system of course for this to work (either set up email or read the notifications from the text file).

**Comment by kassyss** [comment]
I found a simple way to generate passwords for users in file provider.
On Debian, install whois package, it provides mkasswd command
Then :
1. mkpasswd --method=SHA-512 --salt=yoursalt -R 500000 -s
2. Press enter and write your password

The Authelia new password will be "{CRYPT}GeneratedOutput"

Hope it helps

Cheers

**Comment by clems4ever** [comment]
Hello guys, sorry I've been busy lately.

Indeed the file needs to be edited manually and the solution for generating the password was here https://github.com/clems4ever/authelia/blob/master/docs/deployment-dev.md.

The command is `npm run hash-password mypassword`.

Thanks @zegerhoogeboom and @kassyss for your other solutions though.
