### ISSUE TITLE
Protect applications which are using a token authentication header

### ISSUE THREAD

**Issue by SBado** [clems4ever/authelia#422]
Hello @clems4ever ,

I'm using Authelia to protect Node-RED (https://nodered.org/).
Every request to Node-RED is authorized using a bearer token and this is causing the following error to appear in Authelia's log:
 
`Error caught when verifying user authorization: Unable to parse basic auth: Basic prefix not found in authorization header.`

This obviously happens because the authorization header value is "Authorization: Bearer <token_here>".  Is there a reason why Authelia checks for a basic authorization header and fails if it doesn't find one without checking the session cookie first?

In `handler_verify.go`:

```
if hasBasicAuth {
	username, groups, authLevel, err = verifyBasicAuth(proxyAuthorization, *targetURL, ctx)
} else {
	username, groups, authLevel, err = verifyFromSessionCookie(*targetURL, ctx)
}

if err != nil {
	ctx.Logger.Error(fmt.Sprintf("Error caught when verifying user authorization: %s", err))
	ctx.ReplyUnauthorized()
	return
}
```
Imho, in case of error while checking for the authorization header, Authelia should check if the session cookie is present and valid before throwing an error.

This is the "old" Authelia code (Get.ts):
```
async function verifyWithSelectedMethod(req: Express.Request, res: Express.Response,
  vars: ServerVariables, authSession: AuthenticationSession | undefined)
  : Promise<void> {
  if (HasHeader(req, Constants.HEADER_PROXY_AUTHORIZATION)) {
    vars.logger.debug(req, "Got PROXY_AUTHORIZATION header checking basic auth");
    await GetBasicAuth(req, res, vars);
  } else {
    vars.logger.debug(req, "Checking session cookie");
    await GetSessionCookie(req, res, vars, authSession);
  }
}
```
And this is how i patched it to make Authelia work nicely with Node-RED:

```
function verifyWithSelectedMethod(req, res, vars, authSession) {
    return __awaiter(this, void 0, void 0, function* () {
        if (authSession && authSession.userid) {
            yield GetSessionCookie_1.default(req, res, vars, authSession);
        }
        else if (HasHeader_1.default(req, Constants.HEADER_PROXY_AUTHORIZATION)) {
            yield GetBasicAuth_1.default(req, res, vars);
        }
        else {
            throw new Error("No cookie or authorization header detected.");
        }
    });
}
```
What do you think?

**Comment by clems4ever** [comment]
Hello @SBado , do you use Authelia with Basic authorization token sometimes? If it's not the case then you can simply strip the Authorization header from the request sent by the reverse proxy to Authelia.

**Comment by clems4ever** [comment]
In all cases a Header that is not destined to Authelia should not reach it. This is just a matter of reverse proxy config, unless I misunderstood something in your use case. Does it make sense?

**Comment by SBado** [comment]
> Hello @SBado , do you use Authelia with Basic authorization tokens sometimes?

Yes, I do, with a bunch of Android apps.

> In all cases a Header that is not destined to Authelia should not reach it. 

I see your point, but this means that I should disable user authentication inside Node-RED (the Bearer access token is required only when a username and a password are required). Given the fact that I use Node-RED to control my home automation system, I don't feel very confortable about removing an authentication layer, even if there's already Authelia watching over me (I'm paranoid, I know, but just a little bit :) ).

It's not very important, I can always modify the code and try to build a docker image by myself. Thank you anyway!

**Comment by clems4ever** [comment]
I'm not saying that you should disable an authentication layer from your app. I'm simply saying that you should strip the Authorization header from the request between your reverse proxy and Authelia for the given domain serving the app generating the Bearer because this token is not destined to Authelia. By the way, Authelia reads *Proxy-Authorization* header and not *Authorization* as you can see from the code: https://github.com/clems4ever/authelia/blob/a2258aeb7e86843fe4bd6a832458a31ebc046740/server/src/lib/routes/verify/GetBasicAuth.ts#L14

Anyway, stripping the header would be the solution but while checking how I would do it for nginx I can already see an issue. One cannot strip a header in a server block without a third party module... 
https://serverfault.com/questions/928912/how-do-i-remove-a-server-added-header-from-proxied-location
https://github.com/openresty/headers-more-nginx-module.

The closest thing that you can do with nginx is 
```
proxy_set_header            Proxy-Authorization "";
```
but you'll still have the issue.

Which reverse proxy do you use?

**Comment by SBado** [comment]
I'm using Nginx, and I found a solution!

> Authelia reads Proxy-Authorization header and not Authorization

Thank you for remarking this. The only thing I needed was a simple map:

```
map $http_authorization $authelia_authorization {
       ~^Bearer.* "";
       default $http_authorization;    
}
```

And then

`proxy_set_header Proxy-Authorization $authelia_authorization;`

Btw, setting an header to empty string is enough to remove it ([official docs](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header)):

> If the value of a header field is an empty string then this field will not be passed to a proxied server:
> 
> `proxy_set_header Accept-Encoding "";`

Thank you for the support, I'm closing the issue.

**Comment by clems4ever** [comment]
Awesome! Thank you very much for the complementary information. Cheers!
