### ISSUE TITLE
protecting Exchange OWA

### ISSUE THREAD

**Issue by ardegr** [clems4ever/authelia#431]
Hi!
I'm thinking of using Authelia for protecting our OWA web interface. Has anyone already used Authelia for this? Maybe somebody can share some config examples?
Also somebody here already asked how to use Authelia only with OTP, not entering user's main password before OTP. Just want to say that I'm completely agree with that. It would be great to have such an option. For example in my situation user opens OWA's url, enters OTP password firstly in Authelia and then he gets to OWA's web interface and enters his usual credentials there.
I don't think its easy or even possible to make SSO with Authelia and Exchange. And I think it's better not to do that.
Thanks!

**Comment by clems4ever** [comment]
Hello @ardegr , I don't know anyone who has protected OWA with Authelia already. Regarding your requirements, I think the user experience is smoother if the entire authentication process go through the same portal so I don't plan to allow OTP as a single unique factor in Authelia.

Can you elaborate on the why making SSO with Authelia and Exchange would be a bad idea in your opinion? Actually I'd rather think it's the opposite, I think it's the right solution to your problem. It's also been requested by other people for some time now by the way. I think OAuth2 and even OpenID is the right way to go. I'd be more than happy to collaborate and make it work for your use case. What do you think?

Thanks.

**Comment by ardegr** [comment]
@clems4ever , thanks for your reply! I agree with you that user experience would be smoother authenticating on the single form. But users use OWA not very often and it is ok if it will be a little less smoother.
I honestly do not want to offend you in any way or anything like that, but Exchange is a product of another level, I do not want to completely get rid of its login form. I think it is more secure, more robust and has potentially less vulnerabilities (or even if it has, it will be fixed much sooner). Exchange is used by a huge amount of users, so it is absolutely more trusted. Again, no offence, I hope :)
But Authelia would be great as additional factor.
Anyway I will look for some information about using OAuth2 and OpenID with Exchange.
Thanks for your suggestion!

**Comment by nightah** [comment]
I believe ideally when Authelia can support any variant of SAML, OAuth2 or OpenID having Authelia in front of if would be like many of the other MFA solutions out in the wild (a lot which you have to pay for).

Having said that, securing OWA behind Authelia is just as simple as securing any other application.
There are config examples for securing endpoints in the existing documentation.

Because the default nginx doesn't support NTLM authentication there's some additional config required for reverse proxying to Exchange (though this doesn't impact OWA).
Generally this isn't required though because most enterprises have their own load balancers which do support NTLM auth.

**Comment by clems4ever** [comment]
Hello @ardegr , I understand your concerns and I completely agree that MS products are certainly of another level given the number of engineers who work on it and the number of users. I'm security engineer by the way and people from the community have already audited Authelia. It's certainly far from perfect but it's probably better than a lot other opensource projects on the topic I guess.
Anyway, it's not in my plans to have OTP as single factor, I'm sorry.

Don't hesitate to open a new issue if you change your mind or if you need more info.
