### ISSUE TITLE
Support OIDC flow

### ISSUE THREAD

**Issue by tlvenn** [clems4ever/authelia#432]
Bonjour @clems4ever,

I was thinking it would be great if authelia could support OIDC flow so essentially being a OIDC provider itself.

It would open the door to use it to authenticate with Kubernetes and any other tools which can use an OIDC provider to do the auth. Right now I am using dex and their ldap support for that but dex has no support for 2FA and little incentive to move that story forward given the vast majority of users are pairing dex with an OIDC provider which supports and can enforce 2FA Auth (Google, Github, Etc...).

**Comment by clems4ever** [comment]
Hello @tlvenn. That's in my plans for a near future even if Authelia is already usable in Kube with an nginx or traefik ingress controller. There is an example for Kube in the example directory. I also know that some people already worked on a helm chart which is also in my shortlist.

**Comment by tlvenn** [comment]
Just to be clear, my ask is not around deploying authelia on k8s but specifically allowing authelia to be an OIDC provider with or without k8s similarly to how dex can be an OIDC provider on top of LDAP.

**Comment by tlvenn** [comment]
Can probably leverage this package from CoreOS:
> https://godoc.org/github.com/coreos/go-oidc

**Comment by tlvenn** [comment]
Ha it's actually a client so probably not lol..
Seems the way to go is to use the https://godoc.org/golang.org/x/oauth2 package

**Comment by clems4ever** [comment]
Hello @tlvenn , got it. I propose we switch to the following thread to discuss OAuth2 & OpenID in order to have everybody in one place then: https://github.com/clems4ever/authelia/issues/189.
