### ISSUE TITLE
Warning: connect-redis reported a client error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by Iwan-Authelia** [clems4ever/authelia#454]
Hi,

I'm trying to setup a brand new Authelia server but run into trouble. As the documentation on how to set this up is very limited I have started to document it myself which will hopefully help others as well.

This is what I have done so far and on the end is an error I don't understand;

Install a fresh Debian 10
Select 'SSH-server' and 'Standard' nothing else

apt-get install joe net-tools rsync gcc g++ make slapd ldap-utils redis-server curl mariadb-server nginx git apt-transport-https ca-certificates gnupg2 software-properties-common

Enter an Administrator password for slapd (I've used abc123 for all passwords in the test, please use something proper in production)

Install GO;
cd /usr/src/
curl -O https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.13.4.linux-amd64.tar.gz
mkdir ~/work

joe ~/.profile
add the following two lines;
   
export GOPATH=$HOME/work
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

source ~/.profile

Install Docker;
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt-get update
apt-cache policy docker-ce
apt-get install docker-ce docker-compose

Configure ldap server;

cd ~
joe user_group_base.ldif

dn: ou=people,dc=example,dc=com
objectClass: organizationalUnit
ou: people

dn: ou=groups,dc=example,dc=com
objectClass: organizationalUnit
ou: groups

ldapadd -x -D cn=admin,dc=example,dc=com -W -f user_group_base.ldif

#slappasswd (abc123)
#{SSHA}1K/6fJmUfVf9v7aVMNQLON/eGycr2k+s

joe new_user.ldif
dn: uid=iwan,ou=people,dc=example,dc=com
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: shadowAccount
uid: iwan
cn: iwan
givenName: Iwan
sn: Something
userPassword: {SSHA}1K/6fJmUfVf9v7aVMNQLON/eGycr2k+s
loginShell: /bin/bash
uidNumber: 10000
gidNumber: 10000
homeDirectory: /home/iwan
shadowMax: 60
shadowMin: 1
shadowWarning: 7
shadowInactive: 7
shadowLastChange: 0
mail: iwan@example.com

dn: cn=iwan,ou=groups,dc=example,dc=com
objectClass: posixGroup
cn: iwan
gidNumber: 0
memberUid: iwan

ldapadd -x -D cn=admin,dc=example,dc=com -W -f new_user.ldif

ldapwhoami -vvv -h 127.0.0.1 -D "uid=iwan,ou=people,dc=example,dc=com" -x -W
ldap_initialize( ldap://127.0.0.1 )
Enter LDAP Password: user password
dn:uid=iwan,ou=people,dc=example,dc=com
Result: Success (0)
If you see Result: Success (0) then the password matches.

Configure Redis;
joe /etc/redis/redis.conf;
supervised systemd
requirepass abc123
systemctl restart redis

root@authelia-test-deb10:~# redis-cli
127.0.0.1:6379> auth abc123
OK
127.0.0.1:6379> ping
PONG
127.0.0.1:6379> quit
root@authelia-test-deb10:~#

Configure Mariadb;

root@authelia:/opt# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.41-MariaDB-0+deb9u1 Debian 9.9

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> CREATE DATABASE `authelia`;
Query OK, 1 row affected (0.00 sec)

MariaDB [(none)]> GRANT ALL privileges ON `authelia`.* TO 'authelia'@localhost IDENTIFIED BY 'abc123';
Query OK, 0 rows affected (0.06 sec)

MariaDB [(none)]> exit

Configure Nginx;

unlink /etc/nginx/sites-enabled/default
cd /etc/nginx/sites-available
joe reverse-proxy.conf

server {
        listen 80;
        listen [::]:80;

        server_name authelia.example.com;
        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name authelia.example.com;
        ssl_certificate /etc/nginx/ssl/xxx.example.com.fullchain;
        ssl_certificate_key /etc/nginx/ssl/xxx.example.com.key;

        ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security "max-age=31536000";
        access_log /var/log/nginx/authelia.log combined;
        error_log /var/log/nginx/authelia-error.log;

        location / {
                auth_request /auth;
                auth_request_set $auth_status $upstream_status;
                proxy_pass https://test.example.com/;
                proxy_ssl_certificate /etc/nginx/ssl/xxx.example.com.cert;
                proxy_ssl_certificate_key /etc/nginx/ssl/xxx.example.com.key;
        }
        location = /auth {
                internal;
                proxy_pass https://authelia.example.com:9091;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_set_header X-Original-URI $request_uri;
        }
}

cd /etc/nginx
ln sites-available/reverse-proxy.conf sites-enabled/
systemctl restart nginx

Install Node.JS;

cd /usr/src
curl -sL https://deb.nodesource.com/setup_9.x | bash -
apt-get install nodejs

Authelia;
cd /opt
git clone https://github.com/clems4ever/authelia.git && cd authelia
mkdir /etc/authelia/
joe /etc/authelia/config.yml

###############################################################
#                   Authelia configuration                    #
###############################################################

port: 9091

logs_level: debug
jwt_secret: a_secret
default_redirection_url: https://test.example.com/

totp:
  issuer: Iwan Test

authentication_backend:
  ldap:
    url: ldap://127.0.0.1
    base_dn: dc=example,dc=com
    additional_users_dn: ou=people
    users_filter: uid={0}
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectclass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    user: cn=admin,dc=example,dc=com
    password: abc123

access_control:
  default_policy: two_factor

session:
  name: iwantest_session
  secret: unsecure_session_secret
  expiration: 3600000 # 1 hour
  inactivity: 300000 # 5 minutes
  domain: example.com
  redis:
    host: 127.0.0.1
    port: 6379
    password: abc123

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  mysql:
    host: 127.0.0.1
    port: 3306
    database: authelia
    username: authelia
    password: abc123

notifier:
  smtp:
    username: iwan@example.com
    password: abc123
    secure: true
    host: smtp.example.com
    port: 587
    sender: iwan@example.com

docker run -v /etc/authelia/config.yml:/etc/authelia/config.yml clems4ever/authelia

And this is where I get the error;

root@authelia-test-deb10:/opt/authelia# docker run -v /etc/authelia/config.yml:/etc/authelia/config.yml clems4ever/authelia
Unable to find image 'clems4ever/authelia:latest' locally
latest: Pulling from clems4ever/authelia
88286f41530e: Pull complete
4dab7f8f0899: Pull complete
83dd140a1247: Pull complete
0734a4612f36: Pull complete
66a26b98f4ab: Pull complete
0305a06ac604: Pull complete
2bfc1251fd95: Pull complete
Digest: sha256:1dae9e7261a412f696623501485219b8644ecd1db9dd35ae0c80b98965af539e
Status: Downloaded newer image for clems4ever/authelia:latest
debug: date='Mon Nov 25 2019 02:18:18 GMT+0000 (UTC)' message='User configuration is {
  "port": 9091,
  "logs_level": "debug",
  "jwt_secret": "a_secret",
  "default_redirection_url": "https://test.example.com/",
  "totp": {
    "issuer": "Iwan Test"
  },
  "authentication_backend": {
    "ldap": {
      "url": "ldap://127.0.0.1",
      "base_dn": "dc=example,dc=com",
      "additional_users_dn": "ou=people",
      "users_filter": "uid={0}",
      "additional_groups_dn": "ou=groups",
      "groups_filter": "(&(member={dn})(objectclass=groupOfNames))",
      "group_name_attribute": "cn",
      "mail_attribute": "mail",
      "user": "cn=admin,dc=example,dc=com",
      "password": "*****"
    }
  },
  "access_control": {
    "default_policy": "two_factor",
    "rules": []
  },
  "session": {
    "name": "iwantest_session",
    "secret": "*****",
    "expiration": 3600000,
    "inactivity": 300000,
    "domain": "example.com",
    "redis": {
      "host": "127.0.0.1",
      "port": 6379,
      "password": "abc123"
    }
  },
  "regulation": {
    "max_retries": 3,
    "find_time": 120,
    "ban_time": 300
  },
  "storage": {
    "mysql": {
      "host": "127.0.0.1",
      "port": 3306,
      "database": "authelia",
      "username": "authelia",
      "password": "abc123"
    },
    "local": {
      "in_memory": true
    }
  },
  "notifier": {
    "smtp": {
      "username": "iwan@example.com",
      "password": "*****",
      "secure": true,
      "host": "smtp.example.com",
      "port": 587,
      "sender": "iwan@example.com"
    }
  }
}'
info: date='Mon Nov 25 2019 02:18:19 GMT+0000 (UTC)' message='Starting Authelia...'
info: date='Mon Nov 25 2019 02:18:19 GMT+0000 (UTC)' message='Listening on port 9091...'
Warning: connect-redis reported a client error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

/usr/src/node_modules/connect-redis/lib/connect-redis.js:104
          throw err;
          ^
AbortError: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/usr/src/node_modules/redis/index.js:362:23)
    at RedisClient.connection_gone (/usr/src/node_modules/redis/index.js:664:14)
    at RedisClient.on_error (/usr/src/node_modules/redis/index.js:410:10)
    at Socket.<anonymous> (/usr/src/node_modules/redis/index.js:279:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
root@authelia-test-deb10:/opt/authelia#

**Comment by clems4ever** [comment]
Hello @Iwan-Authelia , you should try to use the network host to reach 127.0.0.1 from within your container. Use the following command: `docker run --host network -v /etc/authelia/config.yml:/etc/authelia/config.yml clems4ever/authelia`

If you don't, your host must be reached using the docker bridge IP.

**Comment by Iwan-Authelia** [comment]
Thanks @clems4ever ! That helped a lot.

It must be --network host though :)

One more small issue;

When sending an email to reset a password the link I get is https://undefined/#/reset-password....

where do I set the undefined part? I assume it's an option in /etc/authelia/config.yml but I can't see it?

**Comment by clems4ever** [comment]
You're welcome!
For your last issue, you are missing some headers targeting Authelia:
X-Forwarded-Proto and X-Forwarded-Host. In the examples they are set to **https** and **login.example.com:8080** for instance.

https://github.com/clems4ever/authelia/blob/a2258aeb7e86843fe4bd6a832458a31ebc046740/server/src/lib/IdentityCheckMiddleware.ts#L116

**Comment by clems4ever** [comment]
Can we close that issue?

**Comment by clems4ever** [comment]
I'm closing it, please reopen it if needed.
