### ISSUE TITLE
Duo API errored

### ISSUE THREAD

**Issue by SBado** [clems4ever/authelia#459]
Hello @clems4ever 
I'm facing an annoying issue that requires me to restart Authelia every now and then.
In short, Duo push authentication stops working. These are the logs I collected:
```
time="2019-11-24T18:56:52Z" level=error msg="Duo API errored: Post https://api-0db7ca94.duosecurity.com/auth/v2/auth: dial tcp: lookup api-0db7ca94.duosecurity.com on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address" method=POST path=/api/secondfactor/duo remote_ip=127.0.0.1
stack="/go/src/app/internal/middlewares/authelia_context.go:58
(*AutheliaCtx).Error\n/go/src/app/internal/handlers/handler_sign_duo.go:37
SecondFactorDuoPost.func1\n/go/src/app/internal/middlewares/require_first_factor.go:14
RequireFirstFactor.func1\n/go/src/app/internal/middlewares/authelia_context.go:43
AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326
(*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123
(*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018
(*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223
(*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195
(*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357
goexit"
```
After restarting Authelia, Duo push authentication starts working again until the next failure. Any thoughts?

**Comment by nightah** [comment]
The error seems to suggest that it can't resolve `api-0db7ca94.duosecurity.com` seems like a transient network issue to do with DNS.

**Comment by SBado** [comment]
@nightah I'm not really sure this is the case. At first I came to the same conclusion, but if I remember well I could ping `api-0db7ca94.duosecurity.com` without any problem. I'll try again the next time the error shows up, just to be sure.

**Comment by nightah** [comment]
I would suggest when the error occurs that you launch `ash` in the container and see if you can resolve that hostname to an IP address.

That could give us some more information to work with. If you can, try to perform authentication again. If not, you likely will see the same error.

**Comment by clems4ever** [comment]
I agree with @nightah but still, Authelia should not crash. I'm having a look.

**Comment by clems4ever** [comment]
@SBado , can you elaborate on what happens after this failure? Can you still interact with the portal or is Authelia completely frozen? Can authenticate with another 2FA method?

**Comment by SBado** [comment]
@nightah as soon as the error shows up again I'll do as you suggest, thank you.
@clems4ever I can still interact with the portal and if I'm not mistaken I can authenticate with another 2FA method (OTP), but I will double check as soon as I can.

For now everything is working fine, I will keep you updated. Thank you.

**Comment by clems4ever** [comment]
Ok @SBado , let us know. Thanks.

**Comment by SBado** [comment]
I found the problem: file `/etc/resolv.conf` inside the docker container was empty, so no damain could be resolved (as @nightah suggested). After a restart of the container, the file was correctly populated again.
Really strange issue, but not caused by Authelia, I guess. Nevertheless, it's better to find the root cause, because if/when this problem pops up I think there's nothing Authelia can do to correct or mitigate it.
Any idea why this could happen?

**Comment by nightah** [comment]
Was the `/etc/resolv.conf` completely empty? If not can you paste an example of what it actually looked like?

**Comment by nightah** [comment]
You could alternatively just dump out the working `resolv.conf` to your host and bind mount it in as read-only so it cannot be modified.

**resolv.conf**
```
search tokyo-3 tokyo-3.wlan tokyo-3.vpn guest eva01 cygnus goomba
nameserver 127.0.0.11
options ndots:0
```

`docker run -v /path/on/host/resolv.conf:/etc/resolv.conf:ro clems4ever/authelia`

**Comment by SBado** [comment]
@nightah `/etc/resolv.conf` was completely empty. About your suggestion to bind the file, docker should already use my host machine's resolv.conf file (after restart they were exactly the same) and it should update it every time the host machine modifies it.
Now I tried to start the container with the `--dns=IP_ADDRESS`, let's see how it goes.

**Comment by nightah** [comment]
> About your suggestion to bind the file, docker should already use my host machine's resolv.conf file (after restart they were exactly the same) and it should update it every time the host machine modifies it.

I do not believe this is true. Docker constructs the resolv.conf based on the hosts resolv.conf. This does not mean it uses your hosts, or that it should/will update it every time the host changes it.

If you make a change to the host and delete and recreate the container it will construct a new one based on the changes in the host. But inside a docker networked container the resolv.conf always points to 127.0.0.11 and will recursively use the hosts DNS if doesn’t get a successful response.

The 127.0.0.11 address is the docker networks internal DNS resolver which allows you to resolve container names inside the docker specified network.

The reason I suggested binding something in, is to ensure the container cannot change it.

Specifying then DNS for the container also should not have an impact to the resolv.conf if the container is in a docker specified network. It should still point to 127.0.0.11 and will recourse through the address you provided for upstream DNS.

**Comment by SBado** [comment]
Well, I'm not a Docker guru, I'm just reporting what I read in the docs ([https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/)). Also, I don't know if it's relevant, but I'm using host networking.
When I say that docker is already using my host machine's `resolv.conf`, I mean that docker is copying its content as it is (host and container's `resolve.conf` are identical, comments included, and no trace of `127.0.0.11`). After using `--dns` options, they are no more equals (in the container, it has a single line: `nameserver IP_ADDRESS_I_SET`, and no more comments).
The reason why I'm not so sure about binding my `resolv.conf` is because I'm afraid it could mess with docker's DNS management mechanism:

> How can Docker supply each container with a hostname and DNS configuration, without having to build a custom image with the hostname written inside? Its trick is to overlay three crucial /etc files inside the container with virtual files where it can write fresh information:
> 
>  /etc/hostname
>  /etc/hosts
>  /etc/resolv.conf
> 
> This arrangement allows Docker to do clever things like keep resolv.conf up to date across all containers when the host machine receives new configuration over DHCP later. The exact details of how Docker maintains these files inside the container can change from one Docker version to the next, so **you should leave the files themselves alone and use the following Docker options instead**.

Options follow, including `--dns`.
Finally:

> Regarding DNS settings, in the absence of the --dns=IP_ADDRESS..., --dns-search=DOMAIN..., or --dns-opt=OPTION... options, Docker makes each container’s /etc/resolv.conf look like the /etc/resolv.conf of the host machine (where the docker daemon runs)

**Comment by nightah** [comment]
@SBado sorry, you're absolutely right in the case of using `network-mode: host`. As my explanations above were related to docker networked containers.

Do your DHCP leases on the host have a low TTL?

You could actually try changing the attribute on your hosts `/etc/resolv.conf` to immutable:
`sudo chattr +i /etc/resolv.conf`

This should prevent the `resolv.conf` from changing, but it seems like something is probably happening on the host which then affects the container.

**Comment by clems4ever** [comment]
@SBado , did you manage to solve your issue?

**Comment by clems4ever** [comment]
@SBado , please re-open the issue if you did not entirely solve it.

**Comment by SBado** [comment]
> @SBado , did you manage to solve your issue?

It seems so, thanks!
