### ISSUE TITLE
Ability to run in "lite" mode

### ISSUE THREAD

**Issue by leodotcloud** [clems4ever/authelia#460]
If I want to use Authelia for Ingress authentication backed by LDAP, I find the use of mysql, redis, etc pretty heavy. Also, I don't even need 2FA when using LDAP backend. Is it possible to provide config options to disable 2FA and storage provider middleware and not have the need to run mysql?

**Comment by nightah** [comment]
You are not required to run [mysql](https://github.com/clems4ever/authelia/blob/master/docs/deployment-dev.md#discard-sql-server) or [redis](https://github.com/clems4ever/authelia/blob/master/docs/deployment-dev.md#discard-redis), however doing so has trade-offs.

Also, it's completely up to you as to how you configure each of your endpoints, if you want them all to be only single factor, make sure under your rules section that you set `policy: one_factor` like the following example:

https://github.com/clems4ever/authelia/blob/1530267b501776c1a26c2305103793490eac7245/config.template.yml#L156-L157

**Comment by clems4ever** [comment]
@leodotcloud , did @nightah answer your questions?

**Comment by clems4ever** [comment]
any news @leodotcloud ?

**Comment by clems4ever** [comment]
Please re-open the issue if the advice did not solve your problem.
