### ISSUE TITLE
Authelia V4 listening on all IP#

### ISSUE THREAD

**Issue by Iwan-Authelia** [clems4ever/authelia#471]
Hi,

I'm testing the Binary artifact V4.

On startup it is set to listen on all IP#'s;

tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      671/./authelia-linu

Would be nice to have an option in the config to have it only listening on localhost.

**Comment by clems4ever** [comment]
Good point.

**Comment by nightah** [comment]
I assume you’re running the binary directly? You are aware that with Docker you can bind it to a single address?

**Comment by Iwan-Authelia** [comment]
@nightah I know you can run it in Docker, but I prefer to run it on bare metal.
I think for many people it would be great to have a binary-bare metal option with a set of working config examples :)
Another 'issue' I found was the lack of documentation of the logs_level: in the config.yml. All examples speak about Debug...

**Comment by clems4ever** [comment]
resolved with #482
