### ISSUE TITLE
Wrong remote_ip

### ISSUE THREAD

**Issue by rostchri** [clems4ever/authelia#499]
I'm using the current clems4ever/authelia:master docker-image and traefik v2. Everything is working so far but I notice that the remote_ip, authelia is reporting, is wrong.

I got the following log-output from authelia:

`
time="2019-12-10T20:07:27+01:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=172.43.0.4
`
`
time="2019-12-10T20:07:27+01:00" level=trace msg="Headers=GET /api/verify?rd=https://authelia.service.mydomain/ HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36\r\nHost: authelia.service.mydomain:9091\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7\r\nCache-Control: max-age=0\r\nReferer: https://authelia.service.mydomain/?rd=https://whoami.service.mydomain/\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: same-site\r\nSec-Fetch-User: ?1\r\nUpgrade-Insecure-Requests: 1\r\nX-Forwarded-For: 10.4.0.66\r\nX-Forwarded-Host: whoami.service.mydomain\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: traefik\r\nX-Forwarded-Uri: /\r\nX-Real-Ip: 10.4.0.66\r\nCookie: authelia_session=EZjOayImHrYewRFewyqaiNcbHlJbwgnI\r\n\r\n" method=GET path=/api/verify remote_ip=172.43.0.4
`
`
time="2019-12-10T20:07:27+01:00" level=trace msg="Inactivity report: Inactivity=0, MaxInactivity=300000" method=GET path=/api/verify remote_ip=172.43.0.4
`
`
time="2019-12-10T20:07:27+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/verify remote_ip=172.43.0.4
`

Traefik is transmitting the correct ip-adress via Header (X-Real-Ip: 10.4.0.66 and X-Forwarded-For: 10.4.0.66) to authelia, but authelia still reports remote_ip=172.43.0.4, which is technically correct but should be reported as remote_ip=10.4.0.66. 

If I lower the logs_level from trace- to info/debug-level the information about the real-ip is lost, which is bad.

**Comment by clems4ever** [comment]
Hello @rostchri , this should fix your issue: https://github.com/clems4ever/authelia/pull/501.

**Comment by clems4ever** [comment]
X-Forwarded-For was already supported but X-Real-IP was also supported in v3 that's why I added it back.

**Comment by clems4ever** [comment]
merged in master

**Comment by clems4ever** [comment]
I will rollback my change. I did not read very carefully and apparently you had X-Forwarded-For set. That should have worked. Let's try to debug further why it's not used as expected.

**Comment by clems4ever** [comment]
This one should eventually fix this display issue: https://github.com/clems4ever/authelia/pull/502

**Comment by rostchri** [comment]
I 've tested pull-request #502 and remote_ip is indeed working now.
remote_ip reports the value of Header: X-Forwarded-For.
Thanks

**Comment by clems4ever** [comment]
Good, then it's merged now. Thank you!
