### ISSUE TITLE
Unable to get redirected after 1FA

### ISSUE THREAD

**Issue by mnorrsken** [clems4ever/authelia#500]
I use Authelia for normal username password auth with OpenLDAP. It's a very sleek application and love the simple UI. However when i use it with traefik:

wiki served at https://wiki.domain.net/

        - "traefik.frontend.auth.forward.address=http://authelia:9091/api/verify?rd=https://auth.domain.net"

I log in and always get stuck on the "register 2fa" process. I want to be able to totally ignore all 2fa and only use LDAP. However after i logged in and go again to "https://wiki.domain.net" i am correctly logged in, so its only the redirection process that i get stuck at.

Please add a configuration directive that does this :)

**Comment by clems4ever** [comment]
Hello @mnorrsken , Authelia definitely supports that use case already.  You're supposed to be redirected after proceeding with the 1st factor if Authelia is configured correctly. So, it's like a configuration issue as the single factor authentication is definitely tested during end-to-end tests.

First, you need to make sure that when you get redirected to https://auth.domain.net the URL is containing the target URL in the rd= query parameter. You should end up with something like that in  the browser URL bar:
https://auth.domain.net?rd=https://mytargetservice.domain.net.

If it's the case please send me the configuration of your instance of Authelia. If it's not the case, some headers might not be forwarded correctly from Traefik. I will require the logs of Authelia and the interesting part of your Traefik configuration.

**Comment by mnorrsken** [comment]
You are correct that there is something other that is wrong. The issue seems to be that at the first redirect i end up at the following:
location: https://auth.domain.net?rd=https:/wiki.domain.net/

Notice the single "/". If i manually replace this with correct double // everything works fine!

Let me research this a bit more, if it's actually my traefik configuration. I will get back to you soon.

**Comment by mnorrsken** [comment]
It seems to be a feature in gorilla/mux used in traefik that removes double slashes from URLs (if not URL encoded).
Im using traefik 1.7(.20) and I solved this by adding the following rule to authelia container:
        - "traefik.frontend.redirect.regex=(.*rd=https:/)([^/].*)"
        - "traefik.frontend.redirect.replacement=$$1/$$2"

**Comment by clems4ever** [comment]
Ok so I think it relates to: https://github.com/clems4ever/authelia/issues/476. I think we can follow up on that one. Thanks for the investigation!
Stay tuned for the resolution with URL encoding.
