### ISSUE TITLE
missing rd parameter on redirect

### ISSUE THREAD

**Issue by AidenPTHuang** [clems4ever/authelia#503]
Hi, I use authelia on traefik. and my app part of docker-compose.yml like below:

I set labels below on my app, then I visit to my app. It will redirect to "https://auth.example.com/" not "https://auth.example.com/?rd=https://myapp.examle.com". I can't redirect to my app due to missing rd parameter after login. 

```
      - "traefik.http.middlewares.auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.example.com/%23/"
      - "traefik.http.middlewares.auth.forwardauth.trustforwardheader=true"
      - "traefik.http.middlewares.auth.forwardauth.authresponseheaders=X-Forwarded-User"
```

Is there anything I miss to set?

**Comment by AidenPTHuang** [comment]
I found that it will hit "https://auth.example.com/#?rd=https://myapp.examle.com" then redirect to "https://auth.example.com". How to remove "#"?

**Comment by clems4ever** [comment]
Please remove /%23/ from the URL. It's not necessary anymore.

**Comment by AidenPTHuang** [comment]
@clems4ever ok, thanks.
