### ISSUE TITLE
V4: initializing of sqlite db not working

### ISSUE THREAD

**Issue by mamema** [clems4ever/authelia#504]
Hi,

i'm using the local file based approach (coming from v3.16)

configuration.yml:

`# You must use only an available configuration: local, sql`
`storage:`
 ` # The directory where the DB files will be saved`
 `  local:`
  ` path: /var/lib/authelia/db.sqlite3`

which leads to:

log:

`2019-12-11   11:36:09,stdout,[31mFATA[0m[0000] Unable to initialize SQLite   database /var/lib/authelia/db.sqlite3: unable to open database file    [31mstack[0m="/go/src/app/internal/storage/sqlite_provider.go:44         NewSQLiteProvider\n/go/src/app/cmd/authelia/main.go:74                        startServer\n/go/src/app/cmd/authelia/main.go:108                       main.func1\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830   (*Command).execute\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914   (*Command).ExecuteC\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864   main\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864   (*Command).Execute\n/usr/local/go/src/runtime/proc.go:203                      main\n/usr/local/go/src/runtime/asm_amd64.s:1357               goexit"
--`

**Comment by clems4ever** [comment]
Hello @mamema , can you please reformat the issue so that it's readable?

**Comment by CHBMB** [comment]
Hi @clems4ever,

I'm also seeing this.  I'm trying to set up a fresh Authelia V4 instance.

With this as a docker run command

```
docker run -d 
--name='authelia-v4' 
--net='docker' 
-p '8080:8080/tcp' 
-v '/opt/authelia-v4/configuration.yml':'/etc/authelia/configuration.yml'
-v '/opt/authelia/store/':'/var/lib/authelia/store'
'clems4ever/authelia'
```

My `configuration.yml` is migrated directly from a working v3 container, with just the addition of a  
line:

```
jwt_secret: supersecretjwtsecret
```
and including this as a backend:

```
# You must use only an available configuration: local, mongo
storage:
  # The directory where the DB files will be saved
  local:
    path: /var/lib/authelia/store
```

Logs (formatted as best as I can. ;)
```
time="2019-12-15T18:11:23Z" level=info 
msg="Logging severity set to debug"
time="2019-12-15T18:11:23Z" level=fatal 
msg="Unable to initialize SQLite database /var/lib/authelia/store: unable to open database file" stack="/go/src/app/internal/storage/sqlite_provider.go:44 
NewSQLiteProvider\n/go/src/app/cmd/authelia/main.go:74 
startServer\n/go/src/app/cmd/authelia/main.go:108 
main.func1\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 (*Command).execute\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 (*Command).ExecuteC\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864 
main\n/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864 
(*Command).Execute\n/usr/local/go/src/runtime/proc.go:203 
main\n/usr/local/go/src/runtime/asm_amd64.s:1357 goexit"
```

**Comment by nightah** [comment]
@CHBMB your configuration is incorrect for the storage backend, you are still pointing it to the `/var/lib/authelia/store` directory.

Remap to `/var/lib/authelia/` and make sure the config file reads similar to below:

```yaml
storage:
  # The directory where the DB files will be saved
  local:
    path: /var/lib/authelia/db.sqlite3
```

**Comment by mamema** [comment]
this was also my problem. Docker starting now. Beginning to test.
Suggestion: The config steps are not clear for v4. It's a lot gueswork at the moment......would help to update the wiki

**Comment by clems4ever** [comment]
Hello @mamema , I agree, a clear error message at least would have helped. I put it on top of my todo. Thanks.

Thanks @nightah by the way.

**Comment by mamema** [comment]
Sure. But this i guess is a "lost in translation" issue. After your advice to reformat my topic, i was doing my very best. The logs from synology devices (there where my "fun" is happening) are very difficult to get and ex/import into clear format.

**Comment by nightah** [comment]
Part of the issue is that there is no clear or concise bug template. That’s something we will look into very soon so we can request all the relevant information we need at a minimum to help diagnose issues.

So that’s on us! Stay tuned :).
