### ISSUE TITLE
Changing the 2factor does not work (in combination with postgres)

### ISSUE THREAD

**Issue by jegger** [clems4ever/authelia#505]
I have authelia configured to use postgres as its storage-backend.

When I change the TOTP to Security-key for a user, the authelia logs spit out: 
`ERRO[0028] Unable to save new prefered 2FA method: pq: column "method" of relation "user_preferences" does not exist`

However, when I create that missing col 'method' in 'user_preferences' by hand, it works.
Example: `ALTER TABLE user_preferences add column method VARCHAR;`
(Hint: I can see a 'second_factor_method' col in that table)

=> I tried it with the docker images tags: master and v4.0.0-alpha2

**Comment by n4kre** [comment]
Hi @clems4ever,

Same issue there, but I did not try creating a `method` column.
I couldn't find any refrence to such a column in `sql_provider.go `, though `user_preferences ` is indeed present.

**Comment by clems4ever** [comment]
This issue is fixed by https://github.com/clems4ever/authelia/pull/509
