### ISSUE TITLE
Create a tool to generate configuration documentation based on annotations

### ISSUE THREAD

**Issue by clems4ever** [clems4ever/authelia#60]

**Comment by jkaberg** [comment]
@clems4ever great idea. however perhaps take it one step further and create an "admin area" (web ui) where admins can define the options currently located in the config? an simple one page setup where all config options is present is what I had in mind :smile:

**Comment by clems4ever** [comment]
Hello @jkaberg, you are reading in my mind! I had in mind to create this "admin area" to allow an admin to unban users who performed too many wrong authentications.
But indeed, it could also be used to define the settings. However this is a nice to have for the moment.

**Comment by clems4ever** [comment]
I'm closing this issue in favor of https://github.com/clems4ever/authelia/issues/303.
