### ISSUE TITLE
OAuth endpoint

### ISSUE THREAD

**Issue by w9n** [clems4ever/authelia#62]
Hi there,

nice Project!

What do you think about adding OAuth authorization capabilities, so that this project turns into a single sign on web reverse proxy with 2fa? There is a [node implementation](https://github.com/oauthjs/node-oauth2-server) of [Authorization code grant](https://oauth2.thephpleague.com/authorization-server/auth-code-grant/) which could be [authorized by the existing session](http://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#oauth2server-authorize).

**Comment by clems4ever** [comment]
Hello @w9n,

Thank you for the proposal. I thought about it lately but I wonder if I can use OAuth with my own LDAP and users not having an account on Google. What do you think?
By the way, Authelia is already a SSO reverse proxy with 2FA (supporting TOTP and U2F for the moment). I don't really understand what you meant.

Thanks,
Clément.

**Comment by w9n** [comment]
hi @clems4ever,

you are right authelia is basic SSO, but there are also different definitions which require the user to seamlessly log into various services from its location. This is where OAuth comes into play, which can be implemented by one self without any third party relationship like google. 

Lets say there is a gitlab service running behind the proxy. [Gitlab allows](https://docs.gitlab.com/ce/integration/oauth2_generic.html) to configure log in with a custom OAuth Provider which could be Authelia. What would happen is: 

1.) Click Gitlab login button 
2.) redirect user to Authelia's OAuth Enpoint (which is an Authelia Uri what means the user sends the session to the Endpoint) 
3.) Authelia checks the session  
4.)(if valid) Authelia redirects back to Gitlab's oauth2_generic/callback endpoint

the user is now logged into gitlab with the username of Authelia (backed from ldap) without ever creating an account in gitlab or entering a password (besides entering it one time at the beginning into Authelia).

The redirect request in 2.) could contain the redirect Uri in 4.) but some services like gitlab dont do this and need to previously registered with its callback at the OAuth endpoint. This should probably be realized after an admin panel exists.

**Comment by jkaberg** [comment]
@w9n so basically your suggesting an IDM (Identity management), where Authelia would be the gateway? This is already implemented at other platforms like Keycloak or Gluu.

**Comment by w9n** [comment]
yes, i discovered Keycloak and made good experience with. From a functionality aspect its pretty mature but Authelia is still a nice lightweight alternative to java ee on wildfly.

I will close this issue because i dont think its a good idea to develop in this direction. Authelia fits good somewhere between basic auth and complex IDM.
