### ISSUE TITLE
Support for "Authorization: Bearer xxxxxx" header

### ISSUE THREAD

**Issue by SerialVelocity** [clems4ever/authelia#81]
Hey,

I have programs that want access to authed endpoints. It would be good if you could generate tokens which can be set as a header (or maybe a cookie but I think that is less standard).

The header is usually called "Authorization" and the value is usually "Bearer \<token\>".

Tokens for authentication usually consist of:
  - Name. You usually want to know what the token is for.
  - Access restrictions. For Authelia that would probably be:
      - No user access or group access (used for authorisation only. Might not be useful currently?)
      - User access but no group access (used for generic user access which doesn't belong to a group. Maybe this one isn't useful?)
      - No user access but selected group access (used for restricting to a single application)
      - User access and all groups (this is really just the above bullet but you don't need to type in the group names. This is basically an "admin" token for the user)
  - Expiry. Sometimes you want temporary tokens, sometimes permanent tokens. You'd probably want to make it selectable between:
      - Custom end date
      - Forever
  - Revocation. You need to be able to revoke compromised tokens.

Note: This would require a front-end "management" interface for Authelia.
Note: Expired/revoked tokens are usually left in the UI with the "status" of expired/revoked so it is easy to see why a token has stopped working (and for audit purposes).

Cheers,
Ben

**Comment by clems4ever** [comment]
Hello @SerialVelocity ,
Thank you for the proposal! Does this spec comply with any known RFC, draft or any public document? Can you give me an example of program which requires those tokens?
Thanks,
Clément.

**Comment by SerialVelocity** [comment]
Just from a quick google search, seems like this may be a good place to start for some basic information about tokens:
https://scotch.io/tutorials/the-ins-and-outs-of-token-based-authentication

They recommend JWT tokens at the end but the problem with those tokens is that you can end up with extremely long tokens (which could go over default limits on header length). Your signing key could also be compromised requiring you to invalidate all tokens. Benefits of JWT tokens are that they are stateless. The server only has to verify the token according to its signature and check the revocation list to make sure it hasn't been revoked. Another problem is trying to add it to the revocation list since you have to know the full token or at least some token id otherwise the tokens will have to be stored on in the DB.

Another approach is randomly generated token strings. These are then stored in the database instead of the client and the database contains all information. These are easily revoked and can be updated automatically when the application is updated too (database migrations).

Using the "Authorization" header that I mentioned in the first post is the standard way of doing it while how the back-end deals with the token is usually up to the implementation. I would suggest the randomly generated token strings though as it is usually easier to deal with when implementing things like revocation, and dealing with old tokens as your DB migrations will upgrade them.

A few related RFCs:
https://tools.ietf.org/html/rfc1945#section-11
https://tools.ietf.org/html/rfc6750

You technically aren't OAuth 2, but I think Bearer tokens makes it very easy for users.

**Comment by clems4ever** [comment]
Hello,
My opinion around JWT tokens is a bit mitigated. Here is another interesting post I found a few months ago: http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/. The guy says JWT tokens are for transactions and not for sessions. I'm currently using the implementation of sessions for express. Those are encrypted and not stored on client side. Authelia could then invalidate one if needed but I have not felt the need so far and thus this is not implemented yet.

I guess OAuth would solve the problem, right? I was thinking of implementing it anyway.

**Comment by SerialVelocity** [comment]
I agree with JWT tokens aren't the way to go but I thought I'd give you some info about them anyway (that's why I suggested you should go down the randomly generated token strings route :) ).

OAuth would solve the problem but it is also much more complex to implement. It also needs to be supported in every application which means most open source apps now have to have [oauth2_proxy](https://github.com/bitly/oauth2_proxy) proxying the connections.

Unless you mean just the token generation part of OAuth? If that's the case, it's usually best just to have randomly generated strings as I don't think you gain anything by adding the OAuth complexity.

**Comment by clems4ever** [comment]
@SerialVelocity , to (partly) solve your issue, you can configure your backend to be protected by single factor only and use your base64 encoded username and password in the service trying to authenticate (`-H "Proxy-Authorization: Basic XXXXX"` with curl).

This is not ideal but it can be used until we implement OAuth or app passwords/tokens.

**Comment by clems4ever** [comment]
Hello @SerialVelocity , OAuth2 is now in my shortlist and will therefore make Authelia support Bearer tokens. I propose we switch to the following thread related to the topic: https://github.com/clems4ever/authelia/issues/189.
