### ISSUE TITLE
In-memory NEDB flag not set properly

### ISSUE THREAD

**Issue by SerialVelocity** [clems4ever/authelia#83]
Hey,

While trying to track down the reason why no DB was being written to disk while using local (still not solved, I think I found an issue with the `inMemoryOnly` flag.

It's called `inMemory` here:
https://github.com/clems4ever/authelia/blob/9ac2c808ec259721bf2492ced7b1eb40341c2020/src/server/lib/ServerVariablesHandler.ts#L54

It's called `inMemoryOnly` here:
https://github.com/clems4ever/authelia/blob/9ac2c808ec259721bf2492ced7b1eb40341c2020/src/server/lib/storage/nedb/NedbCollectionFactory.ts#L8

Cheers,
Ben

P.S. Is your local store tested at all? It doesn't seem to be writing anything at all to disk for me :(

**Comment by clems4ever** [comment]
Hello @SerialVelocity , normally this is tested but I will double check. Anyway, this flag is a dev flag now. I should probably mention it in the config file if not already.
thanks.

**Comment by SerialVelocity** [comment]
Yep, don't worry, I'm not using that flag. I just thought I'd _flag_ it to you (pun intended) :)

**Comment by clems4ever** [comment]
@SerialVelocity , you were right, there was a bug, I removed all tests on this flag when I introduced mongo but I've now enforced the correctness of the property with typescript type checking. It that was a bit wonky... Thank you for the ticket.

**Comment by SerialVelocity** [comment]
np
