### ISSUE TITLE
Allow specifying default behaviour for subdomains not listed in config

### ISSUE THREAD

**Issue by SerialVelocity** [clems4ever/authelia#86]
Hey,

It would be great if there was a flag to either deny or allow non-listed subdomains in config. I want everything to call out to Authelia by default and only ask for people to login to those in the config. I think the valid options for this flag would be:
  - No auth needed
  - Logged in
  - Always deny

Cheers,
Ben

P.S. Sorry for all the feature requests, I'm just trying to dump all of the information out of my brain before I forget!

**Comment by clems4ever** [comment]
This is ongoing in #43

**Comment by SerialVelocity** [comment]
@clems4ever Does that ticket include the scenario where users aren't logged in?
